<!DOCTYPE html>
<html lang="en-GB"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Danilo Freire">
  <title>DATASCI 350 – DATASCI 350 - Data Science Computing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-a43b6a543d407931682cae27ef33a0c9.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/multimodal/multimodal.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">DATASCI 350 - Data Science Computing</h1>
  <p class="subtitle">Lecture 26 - Revision: Scaling, SQL and Containers</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Danilo Freire 
</div>
<div class="quarto-title-author-email">
<a href="mailto:danilo.freire@emory.edu">danilo.freire@emory.edu</a>
</div>
        <p class="quarto-title-affiliation">
            Department of Data and Decision Sciences <br> Emory University
          </p>
    </div>
</div>

</section>
<section>
<section id="hello-everyone" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Hello, everyone! 😊</h1>

</section>
<section id="where-we-are" class="slide level2">
<h2>Where we are</h2>
<h3 id="the-last-class-before-the-quiz-and-the-project">The last class before the quiz and the project</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>The eight modules so far:
<ul>
<li><span class="alert">Introduction</span>: how a computer stores and runs your code</li>
<li><span class="alert">Command line and version control</span>: Bash, Git, GitHub</li>
<li><span class="alert">Reproducible research</span>: Quarto and project structure</li>
<li><span class="alert">AI-assisted programming</span>: local models, APIs, RAG</li>
<li><span class="alert">Cloud computing</span>: EC2, S3, and a bill you control</li>
<li><span class="alert">Getting data from the web</span>: APIs, JSON, a saved snapshot</li>
<li><span class="alert">Scaling and performance</span>: joblib, Dask, DuckDB</li>
<li><span class="alert">Containers</span>: environments and Docker</li>
</ul></li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>Today we revise the last two modules</li>
<li><span class="alert">Quiz 05</span> covers Lectures 21, 22, 23 and 25</li>
<li>The <span class="alert">final project</span> is due on the last day of class, and it must render inside a container</li>
</ul>
<div style="text-align: center; margin-top: 10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/table-reproducibility.jpg"><img data-src="figures/table-reproducibility.jpg" style="width:66.0%"></a></p>
<div style="font-size: 17px;">
<p>Source: <a href="https://book.the-turing-way.org/reproducible-research/overview/overview-definitions">The Turing Way Community (2025)</a></p>
</div>
</div>
</div></div>
</div>
</section>
<section id="lecture-overview" class="slide level2">
<h2>Lecture overview</h2>
<h3 id="what-we-will-cover-today">What we will cover today</h3>
<div style="margin-top: 40px; font-size: 24px;">
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="alert">1. Scaling and performance</span></p>
<ul>
<li>Parallel tools, Big O and Amdahl, the GIL, Dask</li>
</ul>
<p><span class="alert">2. SQL revision</span></p>
<ul>
<li>The query order, <code>WHERE</code> and <code>HAVING</code>, <code>COUNT</code>, joins</li>
</ul>
<p><span class="alert">3. SQL practice</span></p>
<ul>
<li>Two exercises, about ten minutes</li>
</ul>
</div><div class="column" style="width:50%;">
<p><span class="alert">4. Containers</span></p>
<ul>
<li>Pinning an environment</li>
<li>The project Dockerfile, and running it</li>
<li>The project checklist</li>
</ul>
<p><span class="alert">5. Quiz 05 preparation</span></p>
<ul>
<li>What each lecture brings, and five Dockerfile questions</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="scaling-and-performance" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Scaling and performance ⚡</h1>

</section>
<section id="parallel-work-and-its-tools" class="slide level2">
<h2>Parallel work and its tools</h2>
<h3 id="lecture-21-map-joblib-and-concurrent.futures">Lecture 21: <code>map</code>, <code>joblib</code> and <code>concurrent.futures</code></h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert">Serial</span>: one line after another</li>
<li><span class="alert">Parallel</span>: independent tasks at the same time, on several cores</li>
<li><span class="alert">Embarrassingly parallel</span>: the tasks share nothing and need no result from each other</li>
<li>Before parallelising, ask: are the tasks independent? Is each one big enough to be worth a worker?</li>
</ul>
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a></a><span class="im">from</span> joblib <span class="im">import</span> Parallel, delayed</span>
<span id="cb1-2"><a></a></span>
<span id="cb1-3"><a></a><span class="kw">def</span> bar(x):</span>
<span id="cb1-4"><a></a>    <span class="cf">return</span> x <span class="op">*</span> x</span>
<span id="cb1-5"><a></a></span>
<span id="cb1-6"><a></a>Parallel(n_jobs<span class="op">=-</span><span class="dv">1</span>)(delayed(bar)(x) <span class="cf">for</span> x <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">6</span>))</span>
<span id="cb1-7"><a></a><span class="co"># [0, 1, 4, 9, 16, 25]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Four calls in parallel never reach a full 4×: starting workers takes time</li>
</ul>
</div><div class="column" style="width:48%;">
<div style="text-align: center; font-size: 20px; margin-top: 10px; margin-bottom: 25px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Your task</th>
<th>Tool</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number crunching</td>
<td><code>ProcessPoolExecutor</code></td>
</tr>
<tr class="even">
<td>Downloading many URLs</td>
<td><code>ThreadPoolExecutor</code></td>
</tr>
<tr class="odd">
<td>sklearn, numeric loops</td>
<td><code>joblib</code> (<code>n_jobs=-1</code>)</td>
</tr>
<tr class="even">
<td>Bigger than RAM</td>
<td>Dask</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><span class="alert">CPU-bound</span>: the processor is busy, so use processes</li>
<li><span class="alert">I/O-bound</span>: the program waits for the network or disk, so use threads</li>
<li><code>concurrent.futures</code> ships with Python, so it works where you cannot install anything</li>
</ul>
</div></div>
</div>
</section>
<section id="big-o-and-amdahls-law" class="slide level2">
<h2>Big O and Amdahl’s law</h2>
<h3 id="what-parallelism-can-and-cannot-fix">What parallelism can and cannot fix</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Big O</span>: how the runtime grows with the input size <code>n</code></li>
<li><span class="alert">O(1)</span>, <span class="alert">O(n)</span>, <span class="alert">O(n²)</span>: doubling <code>n</code> costs nothing, twice as much, or four times as much</li>
<li><code>p</code> cores turn O(n) into O(n/p + overhead). The class stays the same</li>
<li>O(n log n) beats a parallel O(n²) on large inputs</li>
<li>Poor candidates for parallelism:
<ul>
<li>Steps that need the result of the step before</li>
<li>Tasks that share a variable, like a running total</li>
<li>Tasks limited by the disk or memory</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="alert">Amdahl’s law</span>: the serial share <span class="math inline">\(s\)</span> limits the speed-up</li>
<li><span class="math inline">\(\text{speedup} = \dfrac{1}{s + p/N}\)</span>, with <span class="math inline">\(p = 1 - s\)</span> and <span class="math inline">\(N\)</span> cores</li>
<li>90% parallel on 8 cores:</li>
</ul>
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a></a>1 / (0.1 + 0.9/8)</span>
<span id="cb2-2"><a></a>  = 1 / 0.2125</span>
<span id="cb2-3"><a></a>  = 4.7x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>The ceiling is <span class="math inline">\(1/s\)</span>: 10× here, and 2× for a program that is 50% serial</li>
<li>Expect this arithmetic in the quiz</li>
</ul>
</div></div>
</div>
</section>
<section id="the-gil" class="slide level2">
<h2>The GIL</h2>
<h3 id="why-one-thread-runs-python-at-a-time">Why one thread runs Python at a time</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>CPython has a <span class="alert">Global Interpreter Lock</span>: one thread runs Python at a time</li>
<li>Threads help when code <span class="alert">waits</span>: the lock is released during downloads</li>
<li>Threads do not help when code <span class="alert">computes</span></li>
<li>For computing, use <span class="alert">processes</span>, each with its own lock</li>
<li>NumPy and DuckDB <span class="alert">release the GIL</span> in their C and C++ code</li>
<li>Python 3.14 has an official <span class="alert">free-threaded build</span>, but not by default</li>
</ul>
</div><div class="column" style="width:48%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a></a><span class="co"># CPU-bound: threads share one lock,</span></span>
<span id="cb3-2"><a></a><span class="co"># so the time barely changes</span></span>
<span id="cb3-3"><a></a><span class="cf">with</span> ThreadPoolExecutor(<span class="dv">4</span>) <span class="im">as</span> ex:</span>
<span id="cb3-4"><a></a>    <span class="bu">list</span>(ex.<span class="bu">map</span>(calculation, chunks))</span>
<span id="cb3-5"><a></a></span>
<span id="cb3-6"><a></a><span class="co"># Processes: four interpreters,</span></span>
<span id="cb3-7"><a></a><span class="co"># four locks, four cores</span></span>
<span id="cb3-8"><a></a><span class="cf">with</span> ProcessPoolExecutor(<span class="dv">4</span>) <span class="im">as</span> ex:</span>
<span id="cb3-9"><a></a>    <span class="bu">list</span>(ex.<span class="bu">map</span>(calculation, chunks))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Swap <code>calculation</code> for a download, and the threads win</li>
<li>Expect a question on which pool fits which task</li>
</ul>
</div></div>
</div>
</section>
<section id="dask-and-which-tool-when" class="slide level2">
<h2>Dask, and which tool when</h2>
<h3 id="lazy-evaluation-and-the-200-million-row-benchmark">Lazy evaluation and the 200-million-row benchmark</h3>
<div style="margin-top: 30px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Dask</span> gives lazy versions of NumPy arrays, pandas DataFrames, and your own functions (<code>delayed</code>)</li>
<li><span class="alert">Lazy</span>: nothing runs until <code>.compute()</code>. Until then, Dask builds a task graph</li>
<li><code>.persist()</code> keeps a small result in memory</li>
<li>Dask <span class="alert">chunks the data</span>, so it can be bigger than your RAM</li>
<li>The <span class="alert">dashboard</span> at <code>localhost:8787</code> shows the tasks live</li>
<li>On data that fits in memory, Dask can be slower than pandas</li>
<li>Parquet cut our January 2000 data from 182 MB to 86 MB</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>Mean <code>value</code> by indicator and decade, on <span class="alert">200,681,600 rows</span>, Apple M5 laptop:</li>
</ul>
<div style="text-align: center; font-size: 22px; margin-top: 10px; margin-bottom: 20px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>pandas</th>
<th>Dask</th>
<th>DuckDB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9.65 s</td>
<td>5.39 s</td>
<td>0.53 s</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>DuckDB reads only the columns it needs, and uses every core</li>
</ul>
<div style="text-align: center; font-size: 20px; margin-top: 15px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Your situation</th>
<th>Reach for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fits in RAM, exploring, plotting</td>
<td>pandas</td>
</tr>
<tr class="even">
<td>One large file on one machine</td>
<td>DuckDB</td>
</tr>
<tr class="odd">
<td>Bigger than the machine, or a cluster</td>
<td>Dask</td>
</tr>
</tbody>
</table>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="sql-revision" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>SQL revision 🦆</h1>

</section>
<section id="how-a-query-runs" class="slide level2">
<h2>How a query runs</h2>
<h3 id="and-why-where-and-having-differ">And why <code>WHERE</code> and <code>HAVING</code> differ</h3>
<div style="margin-top: 30px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/sql-evaluation-order.png"><img data-src="figures/sql-evaluation-order.png" style="width:100.0%"></a></p>
</div>
<ul>
<li>You write <code>SELECT</code> first, but the engine runs it fifth</li>
<li><span class="alert"><code>WHERE</code></span> filters rows before grouping. <span class="alert"><code>HAVING</code></span> filters groups after</li>
<li>So no aggregate can go in <code>WHERE</code>: the groups do not exist yet</li>
<li>Every <code>SELECT</code> column is in <code>GROUP BY</code> or inside an aggregate</li>
<li>DuckDB accepts a <code>SELECT</code> alias in <code>WHERE</code>, but PostgreSQL does not</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource sql number-lines code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a></a><span class="kw">SELECT</span> country,</span>
<span id="cb4-2"><a></a>       <span class="fu">ROUND</span>(<span class="fu">AVG</span>(<span class="fu">value</span>), <span class="dv">0</span>) <span class="kw">AS</span> mean_gdp</span>
<span id="cb4-3"><a></a><span class="kw">FROM</span> wdi</span>
<span id="cb4-4"><a></a><span class="kw">WHERE</span> <span class="kw">indicator</span> <span class="op">=</span> <span class="st">'gdp_per_capita'</span></span>
<span id="cb4-5"><a></a>  <span class="kw">AND</span> <span class="dt">year</span> <span class="op">&gt;=</span> <span class="dv">2010</span></span>
<span id="cb4-6"><a></a><span class="kw">GROUP</span> <span class="kw">BY</span> country</span>
<span id="cb4-7"><a></a><span class="kw">HAVING</span> <span class="fu">AVG</span>(<span class="fu">value</span>) <span class="op">&gt;</span> <span class="dv">60000</span></span>
<span id="cb4-8"><a></a><span class="kw">ORDER</span> <span class="kw">BY</span> mean_gdp <span class="kw">DESC</span></span>
<span id="cb4-9"><a></a><span class="kw">LIMIT</span> <span class="dv">5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>WHERE year &gt;= 2010</code> drops old rows</li>
<li><code>HAVING AVG(value) &gt; 60000</code> drops poorer countries</li>
<li>Monaco, Liechtenstein and Bermuda top the list, all with fewer than 100,000 people</li>
</ul>
</div></div>
</div>
</section>
<section id="count-and-countvalue" class="slide level2">
<h2>COUNT(*) and COUNT(value)</h2>
<h3 id="counting-rows-and-counting-values">Counting rows and counting values</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert"><code>COUNT(*)</code></span> counts rows. <span class="alert"><code>COUNT(value)</code></span> counts rows with a value</li>
<li>The difference is the number of missing values</li>
<li><code>AVG</code>, <code>SUM</code>, <code>MIN</code> and <code>MAX</code> skip missing values without warning</li>
<li>GDP in 2020: 217 rows, but only 208 numbers</li>
<li><code>primary_enrolment_net</code> in 2020: 217 rows and no numbers, so <code>AVG</code> is NULL</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource sql number-lines code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a></a><span class="kw">SELECT</span> <span class="dt">year</span>,</span>
<span id="cb5-2"><a></a>       <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_rows,</span>
<span id="cb5-3"><a></a>       <span class="fu">COUNT</span>(<span class="fu">value</span>) <span class="kw">AS</span> with_value,</span>
<span id="cb5-4"><a></a>       <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="op">-</span> <span class="fu">COUNT</span>(<span class="fu">value</span>) <span class="kw">AS</span> missing</span>
<span id="cb5-5"><a></a><span class="kw">FROM</span> wdi</span>
<span id="cb5-6"><a></a><span class="kw">WHERE</span> <span class="kw">indicator</span> <span class="op">=</span> <span class="st">'internet_users_pct'</span></span>
<span id="cb5-7"><a></a>  <span class="kw">AND</span> <span class="dt">year</span> <span class="kw">IN</span> (<span class="dv">1990</span>, <span class="dv">2000</span>, <span class="dv">2020</span>)</span>
<span id="cb5-8"><a></a><span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dt">year</span></span>
<span id="cb5-9"><a></a><span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dt">year</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Missing: 9 in 1990, 21 in 2000, 33 in 2020. Coverage gets <span class="alert">worse</span></li>
<li>26 countries with a 1990 figure have none for 2020, from Bermuda and Guam to Syria and Yemen</li>
</ul>
</div></div>
</div>
</section>
<section id="the-three-joins" class="slide level2">
<h2>The three joins</h2>
<h3 id="which-rows-survive">Which rows survive</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:58%;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/sql-joins.png"><img data-src="figures/sql-joins.png" style="width:100.0%"></a></p>
</div>
</div><div class="column" style="width:42%;">
<ul>
<li><span class="alert"><code>INNER JOIN</code></span> keeps rows that match on both sides. It filters silently</li>
<li><span class="alert"><code>LEFT JOIN</code></span> keeps the left table whole, with NULL where there is no partner</li>
<li><span class="alert"><code>FULL OUTER JOIN</code></span> keeps everything from both sides</li>
<li>Lecture 22’s tables gave 5, 6 and 8 rows</li>
<li>To choose, ask which table must survive whole</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="sql-practice" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>SQL practice 🧠</h1>

</section>
<section id="the-setup-for-both-exercises" class="slide level2">
<h2>The setup for both exercises</h2>
<h3 id="run-this-once">Run this once</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><a href="https://github.com/danilofreire/datasci350/raw/refs/heads/main/lectures/lecture-19/data/wdi_panel.parquet">Download the dataset here</a> or use the path <code>../lecture-19/data/wdi_panel.parquet</code></li>
</ul>
<div style="font-size: 22px;">
<div id="c231742b" class="cell" data-cache="true" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a></a><span class="im">import</span> duckdb</span>
<span id="cb6-2"><a></a></span>
<span id="cb6-3"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb6-4"><a></a><span class="st">    CREATE OR REPLACE VIEW wdi AS</span></span>
<span id="cb6-5"><a></a><span class="st">    SELECT * FROM</span></span>
<span id="cb6-6"><a></a><span class="st">    '../lecture-19/data/wdi_panel.parquet'</span></span>
<span id="cb6-7"><a></a><span class="st">"""</span>)</span>
<span id="cb6-8"><a></a></span>
<span id="cb6-9"><a></a>duckdb.sql(<span class="st">"SELECT COUNT(*) AS n_rows FROM wdi"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>┌────────┐
│ n_rows │
│ int64  │
├────────┤
│  59024 │
└────────┘</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>The panel from Module 06: 59,024 rows of <code>country</code>, <code>iso3</code>, <code>indicator</code>, <code>year</code> and <code>value</code></li>
<li>Eight indicators, including <code>gdp_per_capita</code>, <code>life_expectancy</code>, <code>co2_per_capita</code> and <code>internet_users_pct</code></li>
<li>The second exercise is harder than the first</li>
<li>Work in pairs if you like. We look at the solutions together</li>
</ul>
</div></div>
</div>
</section>
<section id="sec-exercise-01" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="five-minutes">Five minutes</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<p>Which countries emitted the most CO2 per person in 2020?</p>
<ol type="1">
<li>Run the setup cell so the <code>wdi</code> view exists</li>
<li>Keep only the rows for <code>co2_per_capita</code></li>
<li>Keep only the year 2020</li>
<li>Return <code>country</code> and <code>value</code>, rounded to one decimal</li>
<li>Rename the rounded column <code>co2_pc</code></li>
<li>Sort from highest to lowest</li>
<li>Return the top five rows</li>
</ol>
</div><div class="column" style="width:48%;">
<p>What to look for:</p>
<ul>
<li>Two conditions join with <code>AND</code> inside one <code>WHERE</code></li>
<li>Text goes in <span class="alert">single quotes</span>
<ul>
<li>Double quotes mean a column name, and DuckDB will say the column does not exist</li>
</ul></li>
<li>Sorting needs <code>DESC</code>, because <code>ASC</code> is the default</li>
<li>The winner is a Pacific island with fewer than 20,000 people</li>
<li>Four of the five are oil or gas economies</li>
</ul>
<p>Solution and the full output: <a href="#/sec-appendix-01"><span class="button">Appendix 01</span></a></p>
</div></div>
</div>
</section>
<section id="sec-exercise-02" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="five-minutes-1">Five minutes</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<p>Which countries have been the most connected since 2015?</p>
<ol type="1">
<li>Keep only the rows for <code>internet_users_pct</code></li>
<li>Keep only the years from 2015 onwards</li>
<li>Report one row per country</li>
<li>Count how many years have a number in <code>value</code>, and call it <code>n_years</code></li>
<li>Compute the mean of <code>value</code>, rounded to one decimal, as <code>mean_internet</code></li>
<li>Keep the countries with at least 5 years of data and a mean above 95</li>
<li>Sort by the mean, highest first, and return five rows</li>
</ol>
</div><div class="column" style="width:48%;">
<p>What to look for:</p>
<ul>
<li>The filter on <code>year</code> and the two filters on the group go in <span class="alert">different clauses</span></li>
<li><code>COUNT(value)</code> and <code>COUNT(*)</code> disagree here, and only one of them counts years with data</li>
<li>Five countries come back, every one of them above 97%</li>
<li>The list mixes Nordic countries with Gulf states, and one country is neither</li>
<li>An error about an aggregate in <code>WHERE</code> means the evaluation ladder is worth another look</li>
</ul>
<p>Solution and the full output: <a href="#/sec-appendix-02"><span class="button">Appendix 02</span></a></p>
</div></div>
</div>
</section></section>
<section>
<section id="containers-and-docker" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Containers and Docker 🐳</h1>

</section>
<section id="why-code-breaks-and-how-to-pin-it" class="slide level2">
<h2>Why code breaks, and how to pin it</h2>
<h3 id="lecture-23-in-one-slide">Lecture 23 in one slide</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li>“It works on my machine”: your code relies on software you never wrote down</li>
<li><code>print "hello"</code> was valid Python 2. In Python 3 it is a <code>SyntaxError</code></li>
<li>In a 2016 Nature survey, over 70% of researchers had failed to reproduce someone else’s experiment</li>
<li>The ladder: <span class="alert">declare</span> your dependencies, <span class="alert">manage</span> them with a tool, <span class="alert">pin</span> exact versions, then <span class="alert">containerise</span></li>
<li>Your project is on the last step: my machine has only Docker</li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 20px; margin-bottom: 20px;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tool</th>
<th>File you commit</th>
<th>Key commands</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>venv</code> + <code>pip</code></td>
<td><code>requirements.txt</code></td>
<td><code>pip freeze</code>, <code>pip install -r</code></td>
</tr>
<tr class="even">
<td>conda</td>
<td><code>environment.yml</code></td>
<td><code>conda env export --from-history</code></td>
</tr>
<tr class="odd">
<td><code>uv</code></td>
<td><code>pyproject.toml</code>, <code>uv.lock</code></td>
<td><code>uv add</code>, <code>uv sync</code>, <code>uv export</code></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><code>pip freeze</code> inside conda writes <code>@ file:///</code> paths that break elsewhere</li>
<li><code>uv</code> in more detail: <a href="#/sec-appendix-05"><span class="button">Appendix 05</span></a></li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 20px; margin-top: 12px;">
<p>Whichever tool you use, you hand in <span class="alert"><code>requirements.txt</code></span> with <code>==</code> pins, because every Dockerfile reads it</p>
</div>
</div></div>
</div>
</section>
<section id="the-project-dockerfile" class="slide level2">
<h2>The project Dockerfile</h2>
<h3 id="what-each-block-does">What each block does</h3>
<div style="margin-top: 30px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:56%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource dockerfile number-lines code-with-copy"><code class="sourceCode dockerfile"><span id="cb8-1"><a></a><span class="co"># 1. Base image</span></span>
<span id="cb8-2"><a></a><span class="kw">FROM</span> ubuntu:24.04</span>
<span id="cb8-3"><a></a></span>
<span id="cb8-4"><a></a><span class="co"># 2. Build-time settings</span></span>
<span id="cb8-5"><a></a><span class="kw">ENV</span> DEBIAN_FRONTEND=noninteractive</span>
<span id="cb8-6"><a></a><span class="kw">SHELL</span> [<span class="st">"/bin/bash"</span>, <span class="st">"-c"</span>]</span>
<span id="cb8-7"><a></a></span>
<span id="cb8-8"><a></a><span class="co"># 3. System packages</span></span>
<span id="cb8-9"><a></a><span class="kw">RUN</span> <span class="ex">apt-get</span> update <span class="kw">&amp;&amp;</span> <span class="ex">apt-get</span> install <span class="at">-y</span> <span class="pp">[</span><span class="ss">...</span><span class="pp">]</span></span>
<span id="cb8-10"><a></a></span>
<span id="cb8-11"><a></a><span class="co"># 4. Quarto</span></span>
<span id="cb8-12"><a></a><span class="kw">RUN</span> <span class="va">ARCH</span><span class="op">=</span><span class="va">$(</span><span class="ex">dpkg</span> <span class="at">--print-architecture</span><span class="va">)</span> <span class="kw">&amp;&amp;</span> <span class="ex">[...]</span></span>
<span id="cb8-13"><a></a></span>
<span id="cb8-14"><a></a><span class="co"># 5. Python environment</span></span>
<span id="cb8-15"><a></a><span class="kw">RUN</span> <span class="ex">python3</span> <span class="at">-m</span> venv /opt/venv</span>
<span id="cb8-16"><a></a><span class="kw">ENV</span> PATH=<span class="st">"/opt/venv/bin:$PATH"</span></span>
<span id="cb8-17"><a></a><span class="kw">COPY</span> requirements.txt /project/requirements.txt</span>
<span id="cb8-18"><a></a><span class="kw">RUN</span> <span class="ex">pip</span> install <span class="at">--no-cache-dir</span> <span class="at">-r</span> /project/requirements.txt</span>
<span id="cb8-19"><a></a></span>
<span id="cb8-20"><a></a><span class="co"># 6. Project files</span></span>
<span id="cb8-21"><a></a><span class="kw">WORKDIR</span> /project</span>
<span id="cb8-22"><a></a><span class="kw">COPY</span> . /project</span>
<span id="cb8-23"><a></a></span>
<span id="cb8-24"><a></a><span class="co"># 7. Default command</span></span>
<span id="cb8-25"><a></a><span class="kw">ENV</span> QUARTO_PYTHON=/opt/venv/bin/python</span>
<span id="cb8-26"><a></a><span class="kw">CMD</span> [<span class="st">"bash"</span>, <span class="st">"-c"</span>, <span class="st">"quarto render report.qmd &amp;&amp; [...]"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:44%;">
<ul>
<li><span class="alert"><code>FROM</code></span> pins the base image. <code>latest</code> moves, which breaks reproducibility</li>
<li><code>DEBIAN_FRONTEND=noninteractive</code> stops apt asking questions</li>
<li>Quarto 1.10.18 comes as a <code>.deb</code>. <code>dpkg --print-architecture</code> picks arm64 or amd64</li>
<li>Ubuntu protects its own Python, so packages go in a venv at <code>/opt/venv</code>, first on the <code>PATH</code></li>
<li><span class="alert"><code>COPY requirements.txt</code></span> comes before <code>COPY . /project</code>, so editing the report keeps <code>pip install</code> cached</li>
<li>13 instructions, 8 build steps: <code>[1/8]</code> to <code>[8/8]</code></li>
</ul>
</div></div>
</div>
</section>
<section id="building-and-running-the-image" class="slide level2">
<h2>Building and running the image</h2>
<h3 id="image-container-registry-and-the--v-flag">Image, container, registry, and the <code>-v</code> flag</h3>
<div style="margin-top: 30px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>An <span class="alert">image</span> is a read-only template, built from a <code>Dockerfile</code></li>
<li>A <span class="alert">container</span> is a running image. A <span class="alert">registry</span>, like Docker Hub, stores images</li>
<li>A container carries system libraries, the interpreter and your code, and starts in a second</li>
</ul>
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb9-1"><a></a>docker build -t datasci350-project .</span>
<span id="cb9-2"><a></a></span>
<span id="cb9-3"><a></a>docker run --rm \</span>
<span id="cb9-4"><a></a>  -v "$(pwd)/output:/project/output" \</span>
<span id="cb9-5"><a></a>  datasci350-project</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Edit the report and rebuild: almost instant. Edit <code>requirements.txt</code>: pip runs again</li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li><code>--rm</code> deletes the container when it exits</li>
<li><span class="alert"><code>-v host:container</code></span> links a folder on your laptop to one in the container</li>
<li>Without <code>-v</code>, the report renders, then disappears with the container</li>
<li><code>-p host:container</code> does the same for ports. Your project needs only <code>-v</code></li>
<li><span class="alert"><code>.dockerignore</code></span> keeps <code>.git</code>, caches and outputs out of the image</li>
<li>Docker Desktop is free for personal and educational use. OrbStack, Podman and Colima take the same commands</li>
<li>Free Docker Hub: 200 pulls every six hours, 100 without logging in</li>
</ul>
</div></div>
</div>
</section>
<section id="the-project-checklist" class="slide level2">
<h2>The project checklist</h2>
<h3 id="and-the-problems-i-expect-to-hear-about">And the problems I expect to hear about</h3>
<div style="margin-top: 30px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Commit <code>data/raw/</code></span>, and check with <code>git ls-files data/raw</code></li>
<li><span class="alert">Pin every package</span> with <code>==</code>, to a version that exists on PyPI</li>
<li><span class="alert">Test from a fresh clone</span>, in an empty folder</li>
<li>Run <code>ls output</code> after the container exits, and check the file’s timestamp</li>
<li>The five commands in <a href="#/sec-appendix-03"><span class="button">Appendix 03</span></a> are 30% of the project grade</li>
<li>My machine has Docker and nothing else: no Python, no Quarto, no packages</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="alert">Data not committed</span>: the build works, and the run fails with <code>IOException: No files found</code></li>
<li><span class="alert">A pin that does not exist</span>: pip stops the build</li>
<li><span class="alert">No <code>-v</code></span>: the report disappears with the container</li>
<li>Where to find help:
<ul>
<li>Installation errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html#sec-appendix-02">Lecture 23</a>, Appendix 02</li>
<li>Build and run errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html#sec-appendix-02">Lecture 25</a>, Appendix 02</li>
</ul></li>
</ul>
</div></div>
</div>
</section>
<section id="working-in-a-mixed-group" class="slide level2">
<h2>Working in a mixed group</h2>
<h3 id="macos-and-windows-wsl-in-the-same-repository">macOS and Windows (WSL) in the same repository</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li>The container runs <span class="alert">Linux</span>, whatever laptop you use</li>
<li><span class="alert">Match the letter case of file names</span>. macOS treats <code>Data.csv</code> and <code>data.csv</code> as the same file, but Linux does not
<ul>
<li>A path that works on a Mac can fail inside the container</li>
</ul></li>
<li><span class="alert">Keep Linux line endings</span>. The starter’s <code>.gitattributes</code> file does this for you, so do not delete it</li>
<li>On Windows, clone the repository in your <span class="alert">WSL home folder</span> (<code>~/</code>), not under <code>/mnt/c/</code>
<ul>
<li>Turn on WSL integration in Docker Desktop, and run every command in the WSL terminal</li>
</ul></li>
</ul>
</div><div class="column" style="width:45%;">
<ul>
<li><span class="alert">Everyone builds, nobody shares images</span>
<ul>
<li>Each member runs <code>docker build</code> from the shared repository</li>
<li>An image built on an Apple Silicon Mac does not run on most Windows laptops</li>
</ul></li>
<li>You never need to push an image for the project: I build it from your repository</li>
<li>The same advice is in the starter’s <code>README.md</code>, under “Working in a mixed group”</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="quiz-05-and-the-project" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Quiz 05 and the project 📝</h1>

</section>
<section id="what-to-expect" class="slide level2">
<h2>What to expect</h2>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Lecture 21</span>
<ul>
<li>Name the tool for a task and say why</li>
<li>Decide whether a small function is embarrassingly parallel</li>
<li>Do an Amdahl calculation with the numbers given</li>
</ul></li>
<li><span class="alert">Lecture 22</span>
<ul>
<li>Read a query and say what comes back</li>
<li>Fix a query that puts an aggregate in <code>WHERE</code></li>
<li>Say how many rows a given join returns, and what <code>COUNT</code> does with a NULL</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="alert">Lecture 23</span>
<ul>
<li>Match <code>venv</code>, conda and <code>uv</code> to their files</li>
<li>Explain what <code>pip freeze</code> writes and what <code>==</code> means</li>
<li>Define image, container and registry</li>
</ul></li>
<li><span class="alert">Lecture 25</span>
<ul>
<li>Read a <code>Dockerfile</code> block and say what it does</li>
<li>Explain why <code>COPY requirements.txt</code> comes before <code>COPY .</code></li>
<li>Say what happens to the report without <code>-v</code></li>
</ul></li>
</ul>
</div></div>
</div>
</section>
<section id="sec-dockerfile-questions" class="slide level2 scrollable">
<h2>Read this Dockerfile</h2>
<h3 id="five-questions-answers-in-the-appendix">Five questions, answers in the appendix</h3>
<div style="margin-top: 30px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode numberSource dockerfile number-lines code-with-copy"><code class="sourceCode dockerfile"><span id="cb10-1"><a></a><span class="kw">FROM</span> ubuntu:24.04</span>
<span id="cb10-2"><a></a></span>
<span id="cb10-3"><a></a><span class="kw">ENV</span> DEBIAN_FRONTEND=noninteractive</span>
<span id="cb10-4"><a></a></span>
<span id="cb10-5"><a></a><span class="kw">RUN</span> <span class="ex">apt-get</span> update <span class="kw">&amp;&amp;</span> <span class="ex">apt-get</span> install <span class="at">-y</span> <span class="pp">[</span><span class="ss">...</span><span class="pp">]</span></span>
<span id="cb10-6"><a></a></span>
<span id="cb10-7"><a></a><span class="kw">RUN</span> <span class="ex">python3</span> <span class="at">-m</span> venv /opt/venv</span>
<span id="cb10-8"><a></a><span class="kw">ENV</span> PATH=<span class="st">"/opt/venv/bin:$PATH"</span></span>
<span id="cb10-9"><a></a></span>
<span id="cb10-10"><a></a><span class="kw">COPY</span> requirements.txt /project/requirements.txt</span>
<span id="cb10-11"><a></a><span class="kw">RUN</span> <span class="ex">pip</span> install <span class="at">--no-cache-dir</span> <span class="at">-r</span> <span class="dt">\</span></span>
<span id="cb10-12"><a></a>    /project/requirements.txt</span>
<span id="cb10-13"><a></a></span>
<span id="cb10-14"><a></a><span class="kw">WORKDIR</span> /project</span>
<span id="cb10-15"><a></a><span class="kw">COPY</span> . /project</span>
<span id="cb10-16"><a></a></span>
<span id="cb10-17"><a></a><span class="kw">CMD</span> [<span class="st">"bash"</span>, <span class="st">"-c"</span>, <span class="st">"quarto render report.qmd"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<ol type="1">
<li>What does <code>FROM ubuntu:24.04</code> pin, and why do we avoid <code>latest</code>?</li>
<li>Why does <code>COPY requirements.txt</code> come before <code>COPY . /project</code>?</li>
<li>What does <code>ENV PATH="/opt/venv/bin:$PATH"</code> change?</li>
<li>Which line reruns if you edit <code>report.qmd</code>, and which if you edit <code>requirements.txt</code>?</li>
<li>What happens to <code>output/report.html</code> if you run the container without <code>-v</code>?</li>
</ol>
<p>Answers: <a href="#/sec-appendix-04"><span class="button">Appendix 04</span></a></p>
</div></div>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Summary</h1>

</section>
<section id="what-to-revise" class="slide level2">
<h2>What to revise</h2>
<div style="margin-top: 40px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Parallel</span> work: <code>joblib</code>, processes for computing, threads for waiting</li>
<li><span class="alert">Big O</span>: parallelism divides the time, but the class stays the same</li>
<li><span class="alert">Amdahl’s law</span>: 90% parallel on 8 cores gives 4.7×</li>
<li><span class="alert">The GIL</span>: one thread runs Python at a time</li>
<li><span class="alert">Dask</span> is lazy until <code>.compute()</code>. A DuckDB result runs when you print it or call <code>.df()</code></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>The query order: <code>FROM</code>, <code>WHERE</code>, <code>GROUP BY</code>, <code>HAVING</code>, then <code>SELECT</code></li>
<li><code>COUNT(*)</code> counts rows, and <code>COUNT(value)</code> counts values</li>
<li>Joins: 5, 6 and 8 rows on the same two tables</li>
<li><span class="alert"><code>requirements.txt</code></span> with <code>==</code> pins, whichever tool wrote it</li>
<li><span class="alert">Image, container, registry</span>, and the <code>-v</code> flag that saves the report</li>
</ul>
</div></div>
</div>
</section>
<section id="before-we-finish" class="slide level2">
<h2>Before we finish</h2>
<div style="margin-top: 40px; font-size: 24px;">
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li><span class="alert">Thank you for a great semester!</span> 🥳🎉
<ul>
<li>You have gone from <code>cd</code> and <code>ls</code> to shipping an image someone else can run</li>
</ul></li>
<li>We meet on 8 December for a Q&amp;A session and project work time, with no lecture</li>
<li>Test your container from a fresh clone, while there is still time to fix it</li>
<li>Email me before Thursday if a topic is still unclear, and we can meet in office hours</li>
<li>Please fill in the <span class="alert">course evaluation</span>
<ul>
<li>I read every comment, and this course changes every year because of them 😊</li>
</ul></li>
</ul>
</div><div class="column" style="width:45%;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/starter-repo-github-2026.png"><img data-src="figures/starter-repo-github-2026.png" style="width:100.0%"></a></p>
<div style="font-size: 17px;">
<p>Source: <a href="https://github.com/danilofreire/datasci350-project-starter">datasci350-project-starter</a></p>
</div>
</div>
</div></div>
</div>
</section></section>
<section id="thank-you-very-much" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Thank you very much! 🙏</h1>

</section>

<section>
<section id="appendix" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Appendix 📚</h1>

</section>
<section id="sec-appendix-01" class="slide level2">
<h2>Appendix 01: Solution to Exercise 01</h2>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<div style="font-size: 20px;">
<div id="8180869c" class="cell" data-cache="true" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb11-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb11-3"><a></a><span class="st">           ROUND(value, 1) AS co2_pc</span></span>
<span id="cb11-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb11-5"><a></a><span class="st">    WHERE indicator = 'co2_per_capita'</span></span>
<span id="cb11-6"><a></a><span class="st">      AND year = 2020</span></span>
<span id="cb11-7"><a></a><span class="st">    ORDER BY value DESC</span></span>
<span id="cb11-8"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb11-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>┌─────────────────────┬────────┐
│       country       │ co2_pc │
│       varchar       │ double │
├─────────────────────┼────────┤
│ Palau               │   71.7 │
│ Qatar               │   41.3 │
│ Bahrain             │   25.0 │
│ Brunei Darussalam   │   22.6 │
│ Trinidad and Tobago │   21.8 │
└─────────────────────┴────────┘</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><code>WHERE</code> drops every other indicator and every other year</li>
<li><code>ROUND(value, 1)</code> computes a new column, and <code>AS co2_pc</code> names it</li>
<li><code>ORDER BY value DESC</code> sorts on the original column, which works just as well as sorting on the alias</li>
<li>Palau reports 71.7 tonnes per person, almost twice Qatar’s 41.3, with fewer than 20,000 residents and a large tourist economy</li>
<li>Qatar, Bahrain, Brunei and Trinidad and Tobago follow, all of them oil or gas producers</li>
</ul>
<p><a href="#/sec-exercise-01"><span class="button">Back to the exercise</span></a></p>
</div></div>
</div>
</section>
<section id="sec-appendix-02" class="slide level2">
<h2>Appendix 02: Solution to Exercise 02</h2>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<div style="font-size: 20px;">
<div id="203f66e1" class="cell" data-cache="true" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb13-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb13-3"><a></a><span class="st">           COUNT(value) AS n_years,</span></span>
<span id="cb13-4"><a></a><span class="st">           ROUND(AVG(value), 1) AS mean_internet</span></span>
<span id="cb13-5"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb13-6"><a></a><span class="st">    WHERE indicator = 'internet_users_pct'</span></span>
<span id="cb13-7"><a></a><span class="st">      AND year &gt;= 2015</span></span>
<span id="cb13-8"><a></a><span class="st">    GROUP BY country</span></span>
<span id="cb13-9"><a></a><span class="st">    HAVING COUNT(value) &gt;= 5</span></span>
<span id="cb13-10"><a></a><span class="st">       AND AVG(value) &gt; 95</span></span>
<span id="cb13-11"><a></a><span class="st">    ORDER BY mean_internet DESC</span></span>
<span id="cb13-12"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb13-13"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>┌────────────┬─────────┬───────────────┐
│  country   │ n_years │ mean_internet │
│  varchar   │  int64  │    double     │
├────────────┼─────────┼───────────────┤
│ Iceland    │       9 │          98.7 │
│ Bahrain    │       9 │          98.4 │
│ Luxembourg │       9 │          97.9 │
│ Qatar      │       9 │          97.8 │
│ Denmark    │       9 │          97.5 │
└────────────┴─────────┴───────────────┘</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><code>WHERE</code> keeps rows, and both <code>HAVING</code> conditions test the group</li>
<li><code>COUNT(value)</code> returns 9 for each of these countries, so the panel holds 2015 to 2023</li>
<li><code>COUNT(*)</code> would return 9 for every country in the world, including the ones with no numbers at all</li>
<li>Iceland leads at 98.7%, with Bahrain, Luxembourg, Qatar and Denmark behind it</li>
<li><code>ORDER BY</code> names <code>mean_internet</code>, the alias created in <code>SELECT</code></li>
</ul>
<p><a href="#/sec-exercise-02"><span class="button">Back to the exercise</span></a></p>
</div></div>
</div>
</section>
<section id="sec-appendix-03" class="slide level2">
<h2>Appendix 03: Checking your container</h2>
<h3 id="the-commands-i-run-on-your-repository">The commands I run on your repository</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:54%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb15-1"><a></a>git clone &lt;your repo url&gt; fresh-test</span>
<span id="cb15-2"><a></a>cd fresh-test</span>
<span id="cb15-3"><a></a>docker build -t datasci350-project .</span>
<span id="cb15-4"><a></a>docker run --rm \</span>
<span id="cb15-5"><a></a>  -v "$(pwd)/output:/project/output" \</span>
<span id="cb15-6"><a></a>  datasci350-project</span>
<span id="cb15-7"><a></a>open output/report.html</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>The machine has Docker installed and nothing else: no Python, no Quarto, no packages</li>
<li>The build has internet; the run is promised none</li>
</ul>
</div><div class="column" style="width:46%;">
<ul>
<li>Check that the snapshot is committed:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb16-1"><a></a>git ls-files data/raw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>It should print your data files, and an empty answer means the render fails inside the container</li>
<li>Installation errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html#sec-appendix-02">Lecture 23, Appendix 02</a></li>
<li>Build and run errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html#sec-appendix-02">Lecture 25, Appendix 02</a></li>
</ul>
</div></div>
</div>
</section>
<section id="sec-appendix-04" class="slide level2 scrollable">
<h2>Appendix 04: Answers to the Dockerfile questions</h2>
<div style="margin-top: 30px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<ol type="1">
<li><code>FROM ubuntu:24.04</code> pins the base operating system to one Ubuntu release
<ul>
<li><code>latest</code> moves: it resolved to 24.04 last year and to 26.04 today</li>
<li>A base image that moves breaks reproducibility</li>
</ul></li>
<li><code>COPY requirements.txt</code> on its own line gives pip a layer of its own
<ul>
<li>Editing your report leaves that slow <code>pip install</code> cached</li>
</ul></li>
<li><code>ENV PATH="/opt/venv/bin:$PATH"</code> puts the virtual environment first on the <code>PATH</code>
<ul>
<li><code>python</code> and <code>pip</code> then mean the ones in <code>/opt/venv</code>, and Ubuntu’s own Python stays untouched</li>
</ul></li>
</ol>
</div><div class="column" style="width:50%;">
<ol start="4" type="1">
<li>Editing <code>report.qmd</code> misses the cache at <code>COPY . /project</code>, so only that step rebuilds
<ul>
<li>Editing <code>requirements.txt</code> misses at <code>COPY requirements.txt</code>, so pip and everything below it runs again</li>
</ul></li>
<li>Without <code>-v</code> the render succeeds inside the container
<ul>
<li><code>--rm</code> then deletes the container, and the file goes with it</li>
<li><code>ls output</code> on your laptop says there is no such directory</li>
</ul></li>
</ol>
<p><a href="#/sec-dockerfile-questions"><span class="button">Back to the questions</span></a></p>
</div></div>
</div>
</section>
<section id="sec-appendix-05" class="slide level2">
<h2>Appendix 05: <code>uv</code> in more detail</h2>
<h3 id="two-files-four-commands">Two files, four commands</h3>
<div style="margin-top: 30px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb17-1"><a></a>uv init l23-uv-demo --python 3.14</span>
<span id="cb17-2"><a></a>cd l23-uv-demo</span>
<span id="cb17-3"><a></a>uv add polars requests</span>
<span id="cb17-4"><a></a></span>
<span id="cb17-5"><a></a>Resolved 8 packages in 378ms</span>
<span id="cb17-6"><a></a>Installed 7 packages in 10ms</span>
<span id="cb17-7"><a></a> + polars==1.44.2</span>
<span id="cb17-8"><a></a> [...]</span>
<span id="cb17-9"><a></a> + requests==2.34.2</span>
<span id="cb17-10"><a></a></span>
<span id="cb17-11"><a></a>uv sync</span>
<span id="cb17-12"><a></a>Resolved 8 packages in 2ms</span>
<span id="cb17-13"><a></a></span>
<span id="cb17-14"><a></a>uv run python -c \</span>
<span id="cb17-15"><a></a>  "import polars; print(polars.__version__)"</span>
<span id="cb17-16"><a></a>1.44.2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="alert"><code>uv</code></span> is an environment and package manager from Astral, written in Rust</li>
<li>Eight packages (seven, plus the project) resolved in <span class="alert">378 milliseconds</span> in lecture 23</li>
<li><code>uv init</code> starts the project, <code>uv add</code> installs a package and records it</li>
<li><code>uv sync</code> rebuilds the environment from the lock file</li>
<li><code>uv run</code> executes inside that environment, so there is nothing to activate</li>
<li><span class="alert"><code>pyproject.toml</code></span> holds your direct dependencies, and you read and edit it</li>
<li><span class="alert"><code>uv.lock</code></span> holds the exact version and hash of every package, direct or not</li>
<li>Commit both files, and never edit the lock by hand</li>
<li><code>uv export --format requirements-txt --no-hashes &gt; requirements.txt</code> writes the file your Dockerfile reads</li>
</ul>
</div></div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://danilofreire.github.io/datasci350/lectures/lecture-26/26-revision.html">Revision</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/multimodal/multimodal.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, Multimodal, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>