{
  "hash": "63ac47dad4a2b99a9c9315a7e21758cc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: DATASCI 350 - Data Science Computing\nsubtitle: \"Lecture 26 - Revision: Scaling, SQL and Containers\"\nauthor:\n  - name: Danilo Freire\n    email: danilo.freire@emory.edu\n    affiliations: \"Department of Data and Decision Sciences <br> Emory University\"\nformat:\n  clean-revealjs:\n    self-contained: false\n    code-overflow: wrap\n    footer: \"[Revision](https://danilofreire.github.io/datasci350/lectures/lecture-26/26-revision.html)\"\ntransition: slide\ntransition-speed: default\nscrollable: true\nengine: python3\nexecute:\n  freeze: auto\n  cache: true\nrevealjs-plugins:\n  - fontawesome\n  - multimodal\nlang: en-GB\neditor:\n  render-on-save: true\n---\n\n# Hello, everyone! 😊 {background-color=\"#1B3A6B\"}\n\n## Where we are\n### The last class before the quiz and the project\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- The eight modules so far:\n  - [Introduction]{.alert}: how a computer stores and runs your code\n  - [Command line and version control]{.alert}: Bash, Git, GitHub\n  - [Reproducible research]{.alert}: Quarto and project structure\n  - [AI-assisted programming]{.alert}: local models, APIs, RAG\n  - [Cloud computing]{.alert}: EC2, S3, and a bill you control\n  - [Getting data from the web]{.alert}: APIs, JSON, a saved snapshot\n  - [Scaling and performance]{.alert}: joblib, Dask, DuckDB\n  - [Containers]{.alert}: environments and Docker\n:::\n\n:::{.column width=\"48%\"}\n- Today we revise the last two modules\n- [Quiz 05]{.alert} covers Lectures 21, 22, 23 and 25\n- The [final project]{.alert} is due on the last day of class, and it must render inside a container\n\n:::{style=\"text-align: center; margin-top: 10px;\"}\n[![](figures/table-reproducibility.jpg){width=\"66%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/table-reproducibility.jpg\"}\n\n:::{style=\"font-size: 17px;\"}\nSource: [The Turing Way Community (2025)](https://book.the-turing-way.org/reproducible-research/overview/overview-definitions)\n:::\n:::\n:::\n:::\n:::\n\n## Lecture overview\n### What we will cover today\n\n:::{style=\"margin-top: 40px; font-size: 24px;\"}\n:::{.columns}\n::::{.column width=\"50%\"}\n[1. Scaling and performance]{.alert}\n\n- Parallel tools, Big O and Amdahl, the GIL, Dask\n\n[2. SQL revision]{.alert}\n\n- The query order, `WHERE` and `HAVING`, `COUNT`, joins\n\n[3. SQL practice]{.alert}\n\n- Two exercises, about ten minutes\n::::\n\n::::{.column width=\"50%\"}\n[4. Containers]{.alert}\n\n- Pinning an environment\n- The project Dockerfile, and running it\n- The project checklist\n\n[5. Quiz 05 preparation]{.alert}\n\n- What each lecture brings, and five Dockerfile questions\n::::\n:::\n:::\n\n# Scaling and performance ⚡ {background-color=\"#1B3A6B\"}\n\n## Parallel work and its tools\n### Lecture 21: `map`, `joblib` and `concurrent.futures`\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [Serial]{.alert}: one line after another\n- [Parallel]{.alert}: independent tasks at the same time, on several cores\n- [Embarrassingly parallel]{.alert}: the tasks share nothing and need no result from each other\n- Before parallelising, ask: are the tasks independent? Is each one big enough to be worth a worker?\n\n:::{style=\"font-size: 20px;\"}\n```python\nfrom joblib import Parallel, delayed\n\ndef bar(x):\n    return x * x\n\nParallel(n_jobs=-1)(delayed(bar)(x) for x in range(6))\n# [0, 1, 4, 9, 16, 25]\n```\n:::\n\n- Four calls in parallel never reach a full 4×: starting workers takes time\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; font-size: 20px; margin-top: 10px; margin-bottom: 25px;\"}\n| Your task | Tool |\n|---|---|\n| Number crunching | `ProcessPoolExecutor` |\n| Downloading many URLs | `ThreadPoolExecutor` |\n| sklearn, numeric loops | `joblib` (`n_jobs=-1`) |\n| Bigger than RAM | Dask |\n:::\n\n- [CPU-bound]{.alert}: the processor is busy, so use processes\n- [I/O-bound]{.alert}: the program waits for the network or disk, so use threads\n- `concurrent.futures` ships with Python, so it works where you cannot install anything\n:::\n:::\n:::\n\n## Big O and Amdahl's law\n### What parallelism can and cannot fix\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Big O]{.alert}: how the runtime grows with the input size `n`\n- [O(1)]{.alert}, [O(n)]{.alert}, [O(n²)]{.alert}: doubling `n` costs nothing, twice as much, or four times as much\n- `p` cores turn O(n) into O(n/p + overhead). The class stays the same\n- O(n log n) beats a parallel O(n²) on large inputs\n- Poor candidates for parallelism:\n  - Steps that need the result of the step before\n  - Tasks that share a variable, like a running total\n  - Tasks limited by the disk or memory\n:::\n\n:::{.column width=\"50%\"}\n- [Amdahl's law]{.alert}: the serial share $s$ limits the speed-up\n- $\\text{speedup} = \\dfrac{1}{s + p/N}$, with $p = 1 - s$ and $N$ cores\n- 90% parallel on 8 cores:\n\n:::{style=\"font-size: 22px;\"}\n```text\n1 / (0.1 + 0.9/8)\n  = 1 / 0.2125\n  = 4.7x\n```\n:::\n\n- The ceiling is $1/s$: 10× here, and 2× for a program that is 50% serial\n- Expect this arithmetic in the quiz\n:::\n:::\n:::\n\n## The GIL\n### Why one thread runs Python at a time\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- CPython has a [Global Interpreter Lock]{.alert}: one thread runs Python at a time\n- Threads help when code [waits]{.alert}: the lock is released during downloads\n- Threads do not help when code [computes]{.alert}\n- For computing, use [processes]{.alert}, each with its own lock\n- NumPy and DuckDB [release the GIL]{.alert} in their C and C++ code\n- Python 3.14 has an official [free-threaded build]{.alert}, but not by default\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"font-size: 20px;\"}\n```python\n# CPU-bound: threads share one lock,\n# so the time barely changes\nwith ThreadPoolExecutor(4) as ex:\n    list(ex.map(calculation, chunks))\n\n# Processes: four interpreters,\n# four locks, four cores\nwith ProcessPoolExecutor(4) as ex:\n    list(ex.map(calculation, chunks))\n```\n:::\n\n- Swap `calculation` for a download, and the threads win\n- Expect a question on which pool fits which task\n:::\n:::\n:::\n\n## Dask, and which tool when\n### Lazy evaluation and the 200-million-row benchmark\n\n:::{style=\"margin-top: 30px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Dask]{.alert} gives lazy versions of NumPy arrays, pandas DataFrames, and your own functions (`delayed`)\n- [Lazy]{.alert}: nothing runs until `.compute()`. Until then, Dask builds a task graph\n- `.persist()` keeps a small result in memory\n- Dask [chunks the data]{.alert}, so it can be bigger than your RAM\n- The [dashboard]{.alert} at `localhost:8787` shows the tasks live\n- On data that fits in memory, Dask can be slower than pandas\n- Parquet cut our January 2000 data from 182 MB to 86 MB\n:::\n\n:::{.column width=\"50%\"}\n- Mean `value` by indicator and decade, on [200,681,600 rows]{.alert}, Apple M5 laptop:\n\n:::{style=\"text-align: center; font-size: 22px; margin-top: 10px; margin-bottom: 20px;\"}\n| pandas | Dask | DuckDB |\n|---|---|---|\n| 9.65 s | 5.39 s | 0.53 s |\n:::\n\n- DuckDB reads only the columns it needs, and uses every core\n\n:::{style=\"text-align: center; font-size: 20px; margin-top: 15px;\"}\n| Your situation | Reach for |\n|---|---|\n| Fits in RAM, exploring, plotting | pandas |\n| One large file on one machine | DuckDB |\n| Bigger than the machine, or a cluster | Dask |\n:::\n:::\n:::\n:::\n\n# SQL revision 🦆 {background-color=\"#1B3A6B\"}\n\n## How a query runs\n### And why `WHERE` and `HAVING` differ\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n:::{style=\"text-align: center;\"}\n[![](figures/sql-evaluation-order.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sql-evaluation-order.png\"}\n:::\n\n- You write `SELECT` first, but the engine runs it fifth\n- [`WHERE`]{.alert} filters rows before grouping. [`HAVING`]{.alert} filters groups after\n- So no aggregate can go in `WHERE`: the groups do not exist yet\n- Every `SELECT` column is in `GROUP BY` or inside an aggregate\n- DuckDB accepts a `SELECT` alias in `WHERE`, but PostgreSQL does not\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 22px;\"}\n```sql\nSELECT country,\n       ROUND(AVG(value), 0) AS mean_gdp\nFROM wdi\nWHERE indicator = 'gdp_per_capita'\n  AND year >= 2010\nGROUP BY country\nHAVING AVG(value) > 60000\nORDER BY mean_gdp DESC\nLIMIT 5\n```\n:::\n\n- `WHERE year >= 2010` drops old rows\n- `HAVING AVG(value) > 60000` drops poorer countries\n- Monaco, Liechtenstein and Bermuda top the list, all with fewer than 100,000 people\n:::\n:::\n:::\n\n## COUNT(\\*) and COUNT(value)\n### Counting rows and counting values\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [`COUNT(*)`]{.alert} counts rows. [`COUNT(value)`]{.alert} counts rows with a value\n- The difference is the number of missing values\n- `AVG`, `SUM`, `MIN` and `MAX` skip missing values without warning\n- GDP in 2020: 217 rows, but only 208 numbers\n- `primary_enrolment_net` in 2020: 217 rows and no numbers, so `AVG` is NULL\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 22px;\"}\n```sql\nSELECT year,\n       COUNT(*) AS n_rows,\n       COUNT(value) AS with_value,\n       COUNT(*) - COUNT(value) AS missing\nFROM wdi\nWHERE indicator = 'internet_users_pct'\n  AND year IN (1990, 2000, 2020)\nGROUP BY year\nORDER BY year\n```\n:::\n\n- Missing: 9 in 1990, 21 in 2000, 33 in 2020. Coverage gets [worse]{.alert}\n- 26 countries with a 1990 figure have none for 2020, from Bermuda and Guam to Syria and Yemen\n:::\n:::\n:::\n\n## The three joins\n### Which rows survive\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"58%\"}\n:::{style=\"text-align: center;\"}\n[![](figures/sql-joins.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sql-joins.png\"}\n:::\n:::\n\n:::{.column width=\"42%\"}\n- [`INNER JOIN`]{.alert} keeps rows that match on both sides. It filters silently\n- [`LEFT JOIN`]{.alert} keeps the left table whole, with NULL where there is no partner\n- [`FULL OUTER JOIN`]{.alert} keeps everything from both sides\n- Lecture 22's tables gave 5, 6 and 8 rows\n- To choose, ask which table must survive whole\n:::\n:::\n:::\n\n# SQL practice 🧠 {background-color=\"#1B3A6B\"}\n\n## The setup for both exercises\n### Run this once\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Download the dataset here](https://github.com/danilofreire/datasci350/raw/refs/heads/main/lectures/lecture-19/data/wdi_panel.parquet) or use the path `../lecture-19/data/wdi_panel.parquet`\n\n:::{style=\"font-size: 22px;\"}\n\n::: {#c231742b .cell cache='true' execution_count=2}\n``` {.python .cell-code}\nimport duckdb\n\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE VIEW wdi AS\n    SELECT * FROM\n    '../lecture-19/data/wdi_panel.parquet'\n\"\"\")\n\nduckdb.sql(\"SELECT COUNT(*) AS n_rows FROM wdi\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n┌────────┐\n│ n_rows │\n│ int64  │\n├────────┤\n│  59024 │\n└────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"50%\"}\n- The panel from Module 06: 59,024 rows of `country`, `iso3`, `indicator`, `year` and `value`\n- Eight indicators, including `gdp_per_capita`, `life_expectancy`, `co2_per_capita` and `internet_users_pct`\n- The second exercise is harder than the first\n- Work in pairs if you like. We look at the solutions together\n:::\n:::\n:::\n\n## Try it yourself! 🧠 {#sec-exercise-01}\n### Five minutes\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\nWhich countries emitted the most CO2 per person in 2020?\n\n1. Run the setup cell so the `wdi` view exists\n2. Keep only the rows for `co2_per_capita`\n3. Keep only the year 2020\n4. Return `country` and `value`, rounded to one decimal\n5. Rename the rounded column `co2_pc`\n6. Sort from highest to lowest\n7. Return the top five rows\n:::\n\n:::{.column width=\"48%\"}\nWhat to look for:\n\n- Two conditions join with `AND` inside one `WHERE`\n- Text goes in [single quotes]{.alert}\n  - Double quotes mean a column name, and DuckDB will say the column does not exist\n- Sorting needs `DESC`, because `ASC` is the default\n- The winner is a Pacific island with fewer than 20,000 people\n- Four of the five are oil or gas economies\n\nSolution and the full output: [[Appendix 01]{.button}](#sec-appendix-01)\n:::\n:::\n:::\n\n## Try it yourself! 🧠 {#sec-exercise-02}\n### Five minutes\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\nWhich countries have been the most connected since 2015?\n\n1. Keep only the rows for `internet_users_pct`\n2. Keep only the years from 2015 onwards\n3. Report one row per country\n4. Count how many years have a number in `value`, and call it `n_years`\n5. Compute the mean of `value`, rounded to one decimal, as `mean_internet`\n6. Keep the countries with at least 5 years of data and a mean above 95\n7. Sort by the mean, highest first, and return five rows\n:::\n\n:::{.column width=\"48%\"}\nWhat to look for:\n\n- The filter on `year` and the two filters on the group go in [different clauses]{.alert}\n- `COUNT(value)` and `COUNT(*)` disagree here, and only one of them counts years with data\n- Five countries come back, every one of them above 97%\n- The list mixes Nordic countries with Gulf states, and one country is neither\n- An error about an aggregate in `WHERE` means the evaluation ladder is worth another look\n\nSolution and the full output: [[Appendix 02]{.button}](#sec-appendix-02)\n:::\n:::\n:::\n\n# Containers and Docker 🐳 {background-color=\"#1B3A6B\"}\n\n## Why code breaks, and how to pin it\n### Lecture 23 in one slide\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- \"It works on my machine\": your code relies on software you never wrote down\n- `print \"hello\"` was valid Python 2. In Python 3 it is a `SyntaxError`\n- In a 2016 Nature survey, over 70% of researchers had failed to reproduce someone else's experiment\n- The ladder: [declare]{.alert} your dependencies, [manage]{.alert} them with a tool, [pin]{.alert} exact versions, then [containerise]{.alert}\n- Your project is on the last step: my machine has only Docker\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px; margin-bottom: 20px;\"}\n| Tool | File you commit | Key commands |\n|---|---|---|\n| `venv` + `pip` | `requirements.txt` | `pip freeze`, `pip install -r` |\n| conda | `environment.yml` | `conda env export --from-history` |\n| `uv` | `pyproject.toml`, `uv.lock` | `uv add`, `uv sync`, `uv export` |\n:::\n\n- `pip freeze` inside conda writes `@ file:///` paths that break elsewhere\n- `uv` in more detail: [[Appendix 05]{.button}](#sec-appendix-05)\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 20px; margin-top: 12px;\"}\nWhichever tool you use, you hand in [`requirements.txt`]{.alert} with `==` pins, because every Dockerfile reads it\n:::\n:::\n:::\n:::\n\n## The project Dockerfile\n### What each block does\n\n:::{style=\"margin-top: 30px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"56%\"}\n:::{style=\"font-size: 20px;\"}\n```dockerfile\n# 1. Base image\nFROM ubuntu:24.04\n\n# 2. Build-time settings\nENV DEBIAN_FRONTEND=noninteractive\nSHELL [\"/bin/bash\", \"-c\"]\n\n# 3. System packages\nRUN apt-get update && apt-get install -y [...]\n\n# 4. Quarto\nRUN ARCH=$(dpkg --print-architecture) && [...]\n\n# 5. Python environment\nRUN python3 -m venv /opt/venv\nENV PATH=\"/opt/venv/bin:$PATH\"\nCOPY requirements.txt /project/requirements.txt\nRUN pip install --no-cache-dir -r /project/requirements.txt\n\n# 6. Project files\nWORKDIR /project\nCOPY . /project\n\n# 7. Default command\nENV QUARTO_PYTHON=/opt/venv/bin/python\nCMD [\"bash\", \"-c\", \"quarto render report.qmd && [...]\"]\n```\n:::\n:::\n\n:::{.column width=\"44%\"}\n- [`FROM`]{.alert} pins the base image. `latest` moves, which breaks reproducibility\n- `DEBIAN_FRONTEND=noninteractive` stops apt asking questions\n- Quarto 1.10.18 comes as a `.deb`. `dpkg --print-architecture` picks arm64 or amd64\n- Ubuntu protects its own Python, so packages go in a venv at `/opt/venv`, first on the `PATH`\n- [`COPY requirements.txt`]{.alert} comes before `COPY . /project`, so editing the report keeps `pip install` cached\n- 13 instructions, 8 build steps: `[1/8]` to `[8/8]`\n:::\n:::\n:::\n\n## Building and running the image\n### Image, container, registry, and the `-v` flag\n\n:::{style=\"margin-top: 30px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- An [image]{.alert} is a read-only template, built from a `Dockerfile`\n- A [container]{.alert} is a running image. A [registry]{.alert}, like Docker Hub, stores images\n- A container carries system libraries, the interpreter and your code, and starts in a second\n\n:::{style=\"font-size: 22px;\"}\n```text\ndocker build -t datasci350-project .\n\ndocker run --rm \\\n  -v \"$(pwd)/output:/project/output\" \\\n  datasci350-project\n```\n:::\n\n- Edit the report and rebuild: almost instant. Edit `requirements.txt`: pip runs again\n:::\n\n:::{.column width=\"48%\"}\n- `--rm` deletes the container when it exits\n- [`-v host:container`]{.alert} links a folder on your laptop to one in the container\n- Without `-v`, the report renders, then disappears with the container\n- `-p host:container` does the same for ports. Your project needs only `-v`\n- [`.dockerignore`]{.alert} keeps `.git`, caches and outputs out of the image\n- Docker Desktop is free for personal and educational use. OrbStack, Podman and Colima take the same commands\n- Free Docker Hub: 200 pulls every six hours, 100 without logging in\n:::\n:::\n:::\n\n## The project checklist\n### And the problems I expect to hear about\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Commit `data/raw/`]{.alert}, and check with `git ls-files data/raw`\n- [Pin every package]{.alert} with `==`, to a version that exists on PyPI\n- [Test from a fresh clone]{.alert}, in an empty folder\n- Run `ls output` after the container exits, and check the file's timestamp\n- The five commands in [[Appendix 03]{.button}](#sec-appendix-03) are 30% of the project grade\n- My machine has Docker and nothing else: no Python, no Quarto, no packages\n:::\n\n:::{.column width=\"50%\"}\n- [Data not committed]{.alert}: the build works, and the run fails with `IOException: No files found`\n- [A pin that does not exist]{.alert}: pip stops the build\n- [No `-v`]{.alert}: the report disappears with the container\n- Where to find help:\n  - Installation errors: [Lecture 23](https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html#sec-appendix-02), Appendix 02\n  - Build and run errors: [Lecture 25](https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html#sec-appendix-02), Appendix 02\n:::\n:::\n:::\n\n## Working in a mixed group\n### macOS and Windows (WSL) in the same repository\n\n:::{style=\"margin-top: 40px; font-size: 23px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n- The container runs [Linux]{.alert}, whatever laptop you use\n- [Match the letter case of file names]{.alert}. macOS treats `Data.csv` and `data.csv` as the same file, but Linux does not\n  - A path that works on a Mac can fail inside the container\n- [Keep Linux line endings]{.alert}. The starter's `.gitattributes` file does this for you, so do not delete it\n- On Windows, clone the repository in your [WSL home folder]{.alert} (`~/`), not under `/mnt/c/`\n  - Turn on WSL integration in Docker Desktop, and run every command in the WSL terminal\n:::\n\n:::{.column width=\"45%\"}\n- [Everyone builds, nobody shares images]{.alert}\n  - Each member runs `docker build` from the shared repository\n  - An image built on an Apple Silicon Mac does not run on most Windows laptops\n- You never need to push an image for the project: I build it from your repository\n- The same advice is in the starter's `README.md`, under \"Working in a mixed group\"\n:::\n:::\n:::\n\n# Quiz 05 and the project 📝 {background-color=\"#1B3A6B\"}\n\n## What to expect\n\n:::{style=\"margin-top: 40px; font-size: 23px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Lecture 21]{.alert}\n  - Name the tool for a task and say why\n  - Decide whether a small function is embarrassingly parallel\n  - Do an Amdahl calculation with the numbers given\n- [Lecture 22]{.alert}\n  - Read a query and say what comes back\n  - Fix a query that puts an aggregate in `WHERE`\n  - Say how many rows a given join returns, and what `COUNT` does with a NULL\n:::\n\n:::{.column width=\"50%\"}\n- [Lecture 23]{.alert}\n  - Match `venv`, conda and `uv` to their files\n  - Explain what `pip freeze` writes and what `==` means\n  - Define image, container and registry\n- [Lecture 25]{.alert}\n  - Read a `Dockerfile` block and say what it does\n  - Explain why `COPY requirements.txt` comes before `COPY .`\n  - Say what happens to the report without `-v`\n:::\n:::\n:::\n\n## Read this Dockerfile {#sec-dockerfile-questions}\n### Five questions, answers in the appendix\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 20px;\"}\n```dockerfile\nFROM ubuntu:24.04\n\nENV DEBIAN_FRONTEND=noninteractive\n\nRUN apt-get update && apt-get install -y [...]\n\nRUN python3 -m venv /opt/venv\nENV PATH=\"/opt/venv/bin:$PATH\"\n\nCOPY requirements.txt /project/requirements.txt\nRUN pip install --no-cache-dir -r \\\n    /project/requirements.txt\n\nWORKDIR /project\nCOPY . /project\n\nCMD [\"bash\", \"-c\", \"quarto render report.qmd\"]\n```\n:::\n:::\n\n:::{.column width=\"50%\"}\n1. What does `FROM ubuntu:24.04` pin, and why do we avoid `latest`?\n2. Why does `COPY requirements.txt` come before `COPY . /project`?\n3. What does `ENV PATH=\"/opt/venv/bin:$PATH\"` change?\n4. Which line reruns if you edit `report.qmd`, and which if you edit `requirements.txt`?\n5. What happens to `output/report.html` if you run the container without `-v`?\n\nAnswers: [[Appendix 04]{.button}](#sec-appendix-04)\n:::\n:::\n:::\n\n# Summary {background-color=\"#1B3A6B\"}\n\n## What to revise\n\n:::{style=\"margin-top: 40px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Parallel]{.alert} work: `joblib`, processes for computing, threads for waiting\n- [Big O]{.alert}: parallelism divides the time, but the class stays the same\n- [Amdahl's law]{.alert}: 90% parallel on 8 cores gives 4.7×\n- [The GIL]{.alert}: one thread runs Python at a time\n- [Dask]{.alert} is lazy until `.compute()`. A DuckDB result runs when you print it or call `.df()`\n:::\n\n:::{.column width=\"50%\"}\n- The query order: `FROM`, `WHERE`, `GROUP BY`, `HAVING`, then `SELECT`\n- `COUNT(*)` counts rows, and `COUNT(value)` counts values\n- Joins: 5, 6 and 8 rows on the same two tables\n- [`requirements.txt`]{.alert} with `==` pins, whichever tool wrote it\n- [Image, container, registry]{.alert}, and the `-v` flag that saves the report\n:::\n:::\n:::\n\n## Before we finish\n\n:::{style=\"margin-top: 40px; font-size: 24px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n- [Thank you for a great semester!]{.alert} 🥳🎉\n  - You have gone from `cd` and `ls` to shipping an image someone else can run\n- We meet on 8 December for a Q&A session and project work time, with no lecture\n- Test your container from a fresh clone, while there is still time to fix it\n- Email me before Thursday if a topic is still unclear, and we can meet in office hours\n- Please fill in the [course evaluation]{.alert}\n  - I read every comment, and this course changes every year because of them 😊\n:::\n\n:::{.column width=\"45%\"}\n:::{style=\"text-align: center;\"}\n[![](figures/starter-repo-github-2026.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/starter-repo-github-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nSource: [datasci350-project-starter](https://github.com/danilofreire/datasci350-project-starter)\n:::\n:::\n:::\n:::\n:::\n\n# Thank you very much! 🙏 {background-color=\"#1B3A6B\"}\n\n# Appendix 📚 {background-color=\"#1B3A6B\"}\n\n## Appendix 01: Solution to Exercise 01 {#sec-appendix-01}\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#8180869c .cell cache='true' execution_count=3}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           ROUND(value, 1) AS co2_pc\n    FROM wdi\n    WHERE indicator = 'co2_per_capita'\n      AND year = 2020\n    ORDER BY value DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n┌─────────────────────┬────────┐\n│       country       │ co2_pc │\n│       varchar       │ double │\n├─────────────────────┼────────┤\n│ Palau               │   71.7 │\n│ Qatar               │   41.3 │\n│ Bahrain             │   25.0 │\n│ Brunei Darussalam   │   22.6 │\n│ Trinidad and Tobago │   21.8 │\n└─────────────────────┴────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"48%\"}\n- `WHERE` drops every other indicator and every other year\n- `ROUND(value, 1)` computes a new column, and `AS co2_pc` names it\n- `ORDER BY value DESC` sorts on the original column, which works just as well as sorting on the alias\n- Palau reports 71.7 tonnes per person, almost twice Qatar's 41.3, with fewer than 20,000 residents and a large tourist economy\n- Qatar, Bahrain, Brunei and Trinidad and Tobago follow, all of them oil or gas producers\n\n[[Back to the exercise]{.button}](#sec-exercise-01)\n:::\n:::\n:::\n\n## Appendix 02: Solution to Exercise 02 {#sec-appendix-02}\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#203f66e1 .cell cache='true' execution_count=4}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           COUNT(value) AS n_years,\n           ROUND(AVG(value), 1) AS mean_internet\n    FROM wdi\n    WHERE indicator = 'internet_users_pct'\n      AND year >= 2015\n    GROUP BY country\n    HAVING COUNT(value) >= 5\n       AND AVG(value) > 95\n    ORDER BY mean_internet DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n┌────────────┬─────────┬───────────────┐\n│  country   │ n_years │ mean_internet │\n│  varchar   │  int64  │    double     │\n├────────────┼─────────┼───────────────┤\n│ Iceland    │       9 │          98.7 │\n│ Bahrain    │       9 │          98.4 │\n│ Luxembourg │       9 │          97.9 │\n│ Qatar      │       9 │          97.8 │\n│ Denmark    │       9 │          97.5 │\n└────────────┴─────────┴───────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"48%\"}\n- `WHERE` keeps rows, and both `HAVING` conditions test the group\n- `COUNT(value)` returns 9 for each of these countries, so the panel holds 2015 to 2023\n- `COUNT(*)` would return 9 for every country in the world, including the ones with no numbers at all\n- Iceland leads at 98.7%, with Bahrain, Luxembourg, Qatar and Denmark behind it\n- `ORDER BY` names `mean_internet`, the alias created in `SELECT`\n\n[[Back to the exercise]{.button}](#sec-exercise-02)\n:::\n:::\n:::\n\n## Appendix 03: Checking your container {#sec-appendix-03}\n### The commands I run on your repository\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"54%\"}\n```text\ngit clone <your repo url> fresh-test\ncd fresh-test\ndocker build -t datasci350-project .\ndocker run --rm \\\n  -v \"$(pwd)/output:/project/output\" \\\n  datasci350-project\nopen output/report.html\n```\n\n* The machine has Docker installed and nothing else: no Python, no Quarto, no packages\n* The build has internet; the run is promised none\n:::\n\n:::{.column width=\"46%\"}\n* Check that the snapshot is committed:\n\n```text\ngit ls-files data/raw\n```\n\n* It should print your data files, and an empty answer means the render fails inside the container\n* Installation errors: [Lecture 23, Appendix 02](https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html#sec-appendix-02)\n* Build and run errors: [Lecture 25, Appendix 02](https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html#sec-appendix-02)\n:::\n:::\n:::\n\n## Appendix 04: Answers to the Dockerfile questions {#sec-appendix-04}\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n1. `FROM ubuntu:24.04` pins the base operating system to one Ubuntu release\n   - `latest` moves: it resolved to 24.04 last year and to 26.04 today\n   - A base image that moves breaks reproducibility\n2. `COPY requirements.txt` on its own line gives pip a layer of its own\n   - Editing your report leaves that slow `pip install` cached\n3. `ENV PATH=\"/opt/venv/bin:$PATH\"` puts the virtual environment first on the `PATH`\n   - `python` and `pip` then mean the ones in `/opt/venv`, and Ubuntu's own Python stays untouched\n:::\n\n:::{.column width=\"50%\"}\n4. Editing `report.qmd` misses the cache at `COPY . /project`, so only that step rebuilds\n   - Editing `requirements.txt` misses at `COPY requirements.txt`, so pip and everything below it runs again\n5. Without `-v` the render succeeds inside the container\n   - `--rm` then deletes the container, and the file goes with it\n   - `ls output` on your laptop says there is no such directory\n\n[[Back to the questions]{.button}](#sec-dockerfile-questions)\n:::\n:::\n:::\n\n## Appendix 05: `uv` in more detail {#sec-appendix-05}\n### Two files, four commands\n\n:::{style=\"margin-top: 30px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 20px;\"}\n```text\nuv init l23-uv-demo --python 3.14\ncd l23-uv-demo\nuv add polars requests\n\nResolved 8 packages in 378ms\nInstalled 7 packages in 10ms\n + polars==1.44.2\n [...]\n + requests==2.34.2\n\nuv sync\nResolved 8 packages in 2ms\n\nuv run python -c \\\n  \"import polars; print(polars.__version__)\"\n1.44.2\n```\n:::\n:::\n\n:::{.column width=\"50%\"}\n- [`uv`]{.alert} is an environment and package manager from Astral, written in Rust\n- Eight packages (seven, plus the project) resolved in [378 milliseconds]{.alert} in lecture 23\n- `uv init` starts the project, `uv add` installs a package and records it\n- `uv sync` rebuilds the environment from the lock file\n- `uv run` executes inside that environment, so there is nothing to activate\n- [`pyproject.toml`]{.alert} holds your direct dependencies, and you read and edit it\n- [`uv.lock`]{.alert} holds the exact version and hash of every package, direct or not\n- Commit both files, and never edit the lock by hand\n- `uv export --format requirements-txt --no-hashes > requirements.txt` writes the file your Dockerfile reads\n:::\n:::\n:::\n\n",
    "supporting": [
      "26-revision_files"
    ],
    "filters": [],
    "includes": {}
  }
}