<!DOCTYPE html>
<html lang="en-GB"><head>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Danilo Freire">
  <title>DATASCI 350 – DATASCI 350 - Data Science Computing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-697d7d19d47ce5d7df3a97cbd1d3ab58.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/multimodal/multimodal.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">DATASCI 350 - Data Science Computing</h1>
  <p class="subtitle">Lecture 22 - SQL Revision with DuckDB</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Danilo Freire 
</div>
<div class="quarto-title-author-email">
<a href="mailto:danilo.freire@emory.edu">danilo.freire@emory.edu</a>
</div>
        <p class="quarto-title-affiliation">
            Department of Data and Decision Sciences <br> Emory University
          </p>
    </div>
</div>

</section>
<section id="hello-again" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Hello again! 😊</h1>

</section>

<section>
<section id="brief-recap" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Brief recap 📚</h1>

</section>
<section id="parallel-computing-fundamentals" class="slide level2">
<h2>Parallel computing fundamentals</h2>
<h3 id="where-lecture-21-left-us">Where lecture 21 left us</h3>
<div style="margin-top: 30px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Last class: <span class="alert">parallel and scalable computing</span>
<ul>
<li><code>map</code>, <code>joblib</code> and <code>concurrent.futures</code></li>
<li><span class="alert">Big O</span>: parallelism divides the time, but not the growth rate</li>
<li><a href="https://en.wikipedia.org/wiki/Amdahl%27s_law">Amdahl’s law</a>: the serial share limits the speed-up</li>
<li><a href="https://en.wikipedia.org/wiki/Global_interpreter_lock">The GIL</a>: threads for waiting, processes for computing</li>
<li><span class="alert">Dask</span>: lazy arrays and DataFrames for data bigger than RAM</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>Some engines <span class="alert">use all your cores</span> with no setup</li>
<li>DuckDB is one of them, and today we use it to revise <span class="alert">SQL</span></li>
<li>All queries run on the <span class="alert">WDI panel</span> from Lecture 19</li>
<li><a href="https://github.com/danilofreire/datasci350/raw/refs/heads/main/lectures/lecture-19/data/wdi_panel.parquet">Download it here</a> or use the path <code>../lecture-19/data/wdi_panel.parquet</code></li>
</ul>
<div style="text-align: center; margin-top: -10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/parallel.png"><img data-src="figures/parallel.png" style="width:52.0%"></a></p>
</div>
</div></div>
</div>
</section>
<section id="lecture-overview" class="slide level2">
<h2>Lecture overview</h2>
<h3 id="what-we-will-cover-today">What we will cover today</h3>
<div style="margin-top: 12px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="alert">1. Why SQL and why DuckDB</span></p>
<ul>
<li>A declarative language every engine speaks</li>
<li><code>import duckdb</code> is the whole setup</li>
</ul>
<p><span class="alert">2. First queries</span></p>
<ul>
<li><code>SELECT</code>, <code>WHERE</code>, <code>ORDER BY</code>, <code>LIMIT</code></li>
<li><code>IN</code>, <code>BETWEEN</code>, <code>LIKE</code>, and the order a query runs in</li>
</ul>
<p><span class="alert">3. Aggregating</span></p>
<ul>
<li><code>COUNT</code>, <code>AVG</code>, <code>GROUP BY</code>, <code>HAVING</code></li>
<li>What <code>COUNT</code> does when values are missing</li>
</ul>
</div><div class="column" style="width:50%;">
<p><span class="alert">4. NULLs, CASE and windows</span></p>
<ul>
<li><code>IS NULL</code>, <code>COALESCE</code>, income bands with <code>CASE</code></li>
<li>Window functions: a group mean and a rank on every row</li>
</ul>
<p><span class="alert">5. Joins</span></p>
<ul>
<li>Primary keys, foreign keys, and the <code>ON</code> clause</li>
<li><code>INNER</code>, <code>LEFT</code>, <code>FULL OUTER</code> on two tiny tables</li>
</ul>
<p><span class="alert">6. DuckDB and pandas</span></p>
<ul>
<li>Querying a <code>pandas</code> DataFrame by its variable name</li>
<li>Handing a result back with <code>.df()</code></li>
<li>DuckDB on 200 million rows</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="why-sql-why-duckdb" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Why SQL, why DuckDB 🦆</h1>

</section>
<section id="why-sql" class="slide level2">
<h2>Why SQL</h2>
<h3 id="you-describe-the-answer-the-engine-finds-it">You describe the answer, the engine finds it</h3>
<div style="margin-top: 40px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><a href="https://en.wikipedia.org/wiki/SQL">SQL</a> is a language for <span class="alert">asking questions of tables</span></li>
<li>It is <span class="alert">relational</span>: tables of rows and columns, combined with joins</li>
<li>It is <span class="alert">declarative</span>: you say what you want, and the engine decides how
<ul>
<li>No loops, no variables, no input/output code</li>
<li>The engine can reorder the query, skip columns, or use every core</li>
</ul></li>
<li>SQL is <a href="https://en.wikipedia.org/wiki/SQL">about fifty years old</a>, and tech job adverts list it <a href="https://finance.yahoo.com/sectors/technology/articles/research-sql-rivals-python-america-131700698.html">about as often as Python</a></li>
<li><code>SELECT</code>, <code>WHERE</code>, <code>GROUP BY</code> and <code>JOIN</code> work the same in DuckDB, SQLite, PostgreSQL, BigQuery and Snowflake</li>
</ul>
</div><div class="column" style="width:48%;">
<div style="text-align: center; margin-top: -10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/duckdb-docs-sql-2026.png"><img data-src="figures/duckdb-docs-sql-2026.png" style="width:100.0%"></a></p>
<div style="font-size: 17px;">
<p>DuckDB’s SQL introduction: <a href="https://duckdb.org/docs/stable/sql/introduction" class="uri">https://duckdb.org/docs/stable/sql/introduction</a></p>
</div>
</div>
</div></div>
</div>
</section>
<section id="why-duckdb-for-a-revision-class" class="slide level2">
<h2>Why DuckDB for a revision class</h2>
<h3 id="an-in-process-engine-with-no-setup">An in-process engine with no setup</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert">Zero setup</span>: <code>pip install duckdb</code>, then <code>import duckdb</code></li>
<li>Unlike <a href="https://www.postgresql.org/docs/current/admin.html">PostgreSQL</a>, there is no server, user or password</li>
<li><span class="alert">In-process</span>: it runs inside your Python session, <a href="https://www.sqlite.org/">like SQLite</a></li>
<li><span class="alert">Reads files by name</span>: a Parquet or CSV path goes straight in <code>FROM</code></li>
<li>It reads a pandas DataFrame by its variable name too</li>
<li><span class="alert">Columnar</span> and <span class="alert">parallel</span>, so the same <code>GROUP BY</code> works on 200 million rows</li>
<li>Version used here: <a href="https://duckdb.org/2026/03/09/announcing-duckdb-150">DuckDB 1.5.5</a></li>
</ul>
</div><div class="column" style="width:48%;">
<div style="text-align: center; margin-top: -10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/duckdb-home-2026.png"><img data-src="figures/duckdb-home-2026.png" style="width:100.0%"></a></p>
<div style="font-size: 17px;">
<p>Source: <a href="https://duckdb.org" class="uri">https://duckdb.org</a></p>
</div>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="first-queries" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>First queries</h1>

</section>
<section id="what-a-table-is" class="slide level2">
<h2>What a table is</h2>
<h3 id="rows-columns-and-one-value-per-cell">Rows, columns and one value per cell</h3>
<div style="margin-top: 40px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>A <span class="alert">table</span> is a grid: each <span class="alert">row</span> is an observation, each <span class="alert">column</span> a variable</li>
<li>Each column has one <span class="alert">type</span>. Ours are text (<code>VARCHAR</code>), whole numbers (<code>SMALLINT</code>) and decimals (<code>DOUBLE</code>)</li>
<li>Other common types: <code>BOOLEAN</code> (true or false), <code>DATE</code> and <code>TIMESTAMP</code></li>
<li>A cell holds one value, or nothing: <code>NULL</code></li>
<li>The <span class="alert">WDI panel</span>: 217 countries, 8 indicators, 34 years (1990 to 2023)</li>
<li>The number is always in <code>value</code>. The <code>indicator</code> column says what it measures</li>
<li>So most queries start with <code>WHERE indicator = '...'</code>, or they mix dollars with years of life</li>
<li>In pandas terms: a table is a DataFrame, a column is a Series, and there is no index</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="text-align: center; font-size: 23px;">
<p>Six rows of the panel, for Brazil in 2019 and 2020:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>country</th>
<th>iso3</th>
<th>indicator</th>
<th>year</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Brazil</td>
<td>BRA</td>
<td>gdp_per_capita</td>
<td>2019</td>
<td>8771.44</td>
</tr>
<tr class="even">
<td>Brazil</td>
<td>BRA</td>
<td>gdp_per_capita</td>
<td>2020</td>
<td>8435.01</td>
</tr>
<tr class="odd">
<td>Brazil</td>
<td>BRA</td>
<td>internet_users_pct</td>
<td>2019</td>
<td>73.91</td>
</tr>
<tr class="even">
<td>Brazil</td>
<td>BRA</td>
<td>internet_users_pct</td>
<td>2020</td>
<td>81.34</td>
</tr>
<tr class="odd">
<td>Brazil</td>
<td>BRA</td>
<td>life_expectancy</td>
<td>2019</td>
<td>75.81</td>
</tr>
<tr class="even">
<td>Brazil</td>
<td>BRA</td>
<td>life_expectancy</td>
<td>2020</td>
<td>74.51</td>
</tr>
</tbody>
</table>
</div>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 15px;">
<p>No two rows share the same <code>country</code>, <code>indicator</code> and <code>year</code>. Together they identify a row: the idea behind a <span class="alert">primary key</span></p>
</div>
</div></div>
</div>
</section>
<section id="querying-a-parquet-file" class="slide level2">
<h2>Querying a Parquet file</h2>
<h3 id="the-file-path-goes-in-the-from-clause">The file path goes in the FROM clause</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>The WDI panel is a Parquet file with 59,024 rows</li>
<li><a href="https://github.com/danilofreire/datasci350/raw/refs/heads/main/lectures/lecture-19/data/wdi_panel.parquet">Download it here</a> or use the path <code>../lecture-19/data/wdi_panel.parquet</code></li>
<li><code>duckdb.sql()</code> takes a query string and returns a result you can print</li>
<li>The path goes in <span class="alert">single quotes</span>: single quotes mean text, double quotes a column name</li>
<li>No <code>read_parquet</code>, connection or <code>fetchall()</code> needed. DuckDB handles it</li>
<li>The <span class="alert">column types</span> under the names come from the file</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 24px;">
<div id="684bdbc9" class="cell" data-cache="true" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a></a><span class="im">import</span> duckdb</span>
<span id="cb1-2"><a></a></span>
<span id="cb1-3"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb1-4"><a></a><span class="st">    SELECT *</span></span>
<span id="cb1-5"><a></a><span class="st">    FROM '../lecture-19/data/wdi_panel.parquet'</span></span>
<span id="cb1-6"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb1-7"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>┌─────────┬─────────┬────────────────┬───────┬──────────────────┐
│ country │  iso3   │   indicator    │ year  │      value       │
│ varchar │ varchar │    varchar     │ int16 │      double      │
├─────────┼─────────┼────────────────┼───────┼──────────────────┤
│ Aruba   │ ABW     │ co2_per_capita │  1990 │ 3.20303411789078 │
│ Aruba   │ ABW     │ co2_per_capita │  1991 │ 3.43571688721622 │
│ Aruba   │ ABW     │ co2_per_capita │  1992 │  3.6345192377364 │
│ Aruba   │ ABW     │ co2_per_capita │  1993 │ 3.41453484426953 │
│ Aruba   │ ABW     │ co2_per_capita │  1994 │ 3.68322701204975 │
└─────────┴─────────┴────────────────┴───────┴──────────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="creating-a-view" class="slide level2">
<h2>Creating a view</h2>
<h3 id="one-name-for-the-file">One name for the file</h3>
<div style="margin-top: 40px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:44%;">
<ul>
<li>A <span class="alert">view</span> is a saved query that behaves like a table</li>
<li><code>CREATE OR REPLACE VIEW wdi AS ...</code> names the query <code>wdi</code></li>
<li>Later queries say <code>FROM wdi</code>, with no file path</li>
<li>A view holds no data: DuckDB re-reads the file each time</li>
<li><code>OR REPLACE</code> overwrites an old view, so the cell is safe to re-run</li>
<li><span class="alert"><code>COUNT(DISTINCT country)</code></span> counts the different values in a column</li>
<li>The view disappears when Python restarts</li>
</ul>
</div><div class="column" style="width:56%;">
<div style="font-size: 23px;">
<div id="9404b1a2" class="cell" data-cache="true" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb3-2"><a></a><span class="st">    CREATE OR REPLACE VIEW wdi AS</span></span>
<span id="cb3-3"><a></a><span class="st">    SELECT * FROM '../lecture-19/data/wdi_panel.parquet'</span></span>
<span id="cb3-4"><a></a><span class="st">"""</span>)</span>
<span id="cb3-5"><a></a></span>
<span id="cb3-6"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb3-7"><a></a><span class="st">    SELECT COUNT(*) AS n_rows,</span></span>
<span id="cb3-8"><a></a><span class="st">           COUNT(DISTINCT country) AS countries,</span></span>
<span id="cb3-9"><a></a><span class="st">           COUNT(DISTINCT indicator) AS indicators</span></span>
<span id="cb3-10"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb3-11"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>┌────────┬───────────┬────────────┐
│ n_rows │ countries │ indicators │
│ int64  │   int64   │   int64    │
├────────┼───────────┼────────────┤
│  59024 │       217 │          8 │
└────────┴───────────┴────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="describe-and-summarize" class="slide level2">
<h2>DESCRIBE and SUMMARIZE</h2>
<h3 id="two-commands-to-run-before-any-query">Two commands to run before any query</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:44%;">
<ul>
<li>Run both before writing a query, to learn the column names</li>
<li><span class="alert"><code>DESCRIBE</code></span> lists the columns and their types</li>
<li><code>country</code>, <code>iso3</code> and <code>indicator</code> are text (<code>VARCHAR</code>), so filters on them need single quotes</li>
<li><span class="alert"><code>SUMMARIZE</code></span> adds min, max, count and the share of missing values</li>
<li>11.06% of <code>value</code> is missing. <code>country</code> and <code>year</code> have no gaps</li>
<li>Its result is a table, so we can <code>SELECT</code> from it</li>
<li>In pandas: <code>df.dtypes</code> and <code>df.describe()</code></li>
</ul>
</div><div class="column" style="width:56%;">
<div style="font-size: 23px;">
<div id="aaa59798" class="cell" data-cache="true" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a></a>duckdb.sql(<span class="st">"DESCRIBE SELECT * FROM wdi"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ country     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ iso3        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ indicator   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ year        │ SMALLINT    │ YES     │ NULL    │ NULL    │ NULL    │
│ value       │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘</code></pre>
</div>
</div>
<div id="070e2190" class="cell" data-cache="true" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb7-2"><a></a><span class="st">    SELECT column_name, min, max, null_percentage</span></span>
<span id="cb7-3"><a></a><span class="st">    FROM (SUMMARIZE SELECT country, year, value FROM wdi)</span></span>
<span id="cb7-4"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>┌─────────────┬─────────────┬──────────────┬─────────────────┐
│ column_name │     min     │     max      │ null_percentage │
│   varchar   │   varchar   │   varchar    │  decimal(9,2)   │
├─────────────┼─────────────┼──────────────┼─────────────────┤
│ country     │ Afghanistan │ Zimbabwe     │            0.00 │
│ year        │ 1990        │ 2023         │            0.00 │
│ value       │ 0.0         │ 1438069596.0 │           11.06 │
└─────────────┴─────────────┴──────────────┴─────────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="select-aliases-order-by-limit" class="slide level2">
<h2>SELECT, aliases, ORDER BY, LIMIT</h2>
<h3 id="picking-columns-and-sorting-the-result">Picking columns and sorting the result</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:48%;">
<ul>
<li>The query is a Python string passed to <code>duckdb.sql()</code></li>
<li>Keywords are upper case by convention, but <code>select</code> works too, and <code>Country</code> finds <code>country</code></li>
<li><code>SELECT</code> lists the columns you want. <code>*</code> means all of them</li>
<li>It can compute new columns, like <code>ROUND(value, 0)</code></li>
<li><span class="alert"><code>AS</code></span> gives a column a new name, called an <span class="alert">alias</span></li>
<li><span class="alert"><code>ORDER BY value DESC</code></span> sorts high to low. <code>ASC</code>, low to high, is the default</li>
<li><span class="alert"><code>LIMIT</code></span> keeps the first rows, like <code>.head()</code> in pandas</li>
</ul>
</div><div class="column" style="width:52%;">
<div style="font-size: 24px;">
<div id="5ae48150" class="cell" data-cache="true" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb9-2"><a></a><span class="st">    SELECT country, year,</span></span>
<span id="cb9-3"><a></a><span class="st">           ROUND(value, 0) AS gdp_pc</span></span>
<span id="cb9-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb9-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb9-6"><a></a><span class="st">      AND year = 2020</span></span>
<span id="cb9-7"><a></a><span class="st">    ORDER BY value DESC</span></span>
<span id="cb9-8"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb9-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>┌─────────────┬───────┬──────────┐
│   country   │ year  │  gdp_pc  │
│   varchar   │ int16 │  double  │
├─────────────┼───────┼──────────┤
│ Monaco      │  2020 │ 161263.0 │
│ Luxembourg  │  2020 │ 105274.0 │
│ Bermuda     │  2020 │  98846.0 │
│ Isle of Man │  2020 │  86595.0 │
│ Switzerland │  2020 │  86294.0 │
└─────────────┴───────┴──────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="where-with-and-or-and-not" class="slide level2">
<h2>WHERE with AND, OR and NOT</h2>
<h3 id="filtering-rows-with-where">Filtering rows with WHERE</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:48%;">
<ul>
<li><span class="alert"><code>WHERE</code></span> keeps rows where the condition is true, like boolean indexing in pandas</li>
<li>Comparisons: <code>=</code>, <code>&lt;&gt;</code> (not equal), <code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code></li>
<li><span class="alert"><code>AND</code></span> needs both sides true. <span class="alert"><code>OR</code></span> needs either</li>
<li><span class="alert"><code>NOT</code></span> flips a condition: <code>NOT country = 'Japan'</code> would keep only Brazil</li>
<li>Text goes in single quotes, and the match is case-sensitive</li>
<li>The brackets matter, because <code>AND</code> is applied before <code>OR</code></li>
<li>Four rows: Brazil on 6,818 and 8,435, Japan on 31,779 and 35,363</li>
</ul>
</div><div class="column" style="width:52%;">
<div style="font-size: 24px;">
<div id="b1e87090" class="cell" data-cache="true" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb11-2"><a></a><span class="st">    SELECT country, year,</span></span>
<span id="cb11-3"><a></a><span class="st">           ROUND(value, 0) AS gdp_pc</span></span>
<span id="cb11-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb11-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb11-6"><a></a><span class="st">      AND (year = 2000 OR year = 2020)</span></span>
<span id="cb11-7"><a></a><span class="st">      AND (country = 'Brazil' OR country = 'Japan')</span></span>
<span id="cb11-8"><a></a><span class="st">    ORDER BY country, year</span></span>
<span id="cb11-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>┌─────────┬───────┬─────────┐
│ country │ year  │ gdp_pc  │
│ varchar │ int16 │ double  │
├─────────┼───────┼─────────┤
│ Brazil  │  2000 │  6818.0 │
│ Brazil  │  2020 │  8435.0 │
│ Japan   │  2000 │ 31779.0 │
│ Japan   │  2020 │ 35363.0 │
└─────────┴───────┴─────────┘</code></pre>
</div>
</div>
</div>
<div style="background: rgba(230, 57, 70, 0.1); padding: 12px; border-radius: 10px; font-size: 18px; margin-top: 10px;">
<p>Without the brackets, the query returns 496 rows: GDP for every country in 2000, all of Brazil’s 2020 rows, and every Japanese row</p>
</div>
</div></div>
</div>
</section>
<section id="in-and-between" class="slide level2">
<h2>IN and BETWEEN</h2>
<h3 id="shorter-ways-to-write-the-same-conditions">Shorter ways to write the same conditions</h3>
<div style="margin-top: 40px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:46%;">
<ul>
<li><span class="alert"><code>IN</code></span> replaces a chain of <code>OR</code>s on one column</li>
<li><code>country IN ('Brazil', 'China')</code> means <code>country = 'Brazil' OR country = 'China'</code></li>
<li><span class="alert"><code>BETWEEN</code></span> includes both ends: 2018 to 2020 covers three years</li>
<li>The low end goes first. <code>BETWEEN 2020 AND 2018</code> returns nothing</li>
<li>In pandas: <code>.isin([...])</code> and <code>.between(2018, 2020)</code></li>
<li>Six countries × three years = 18 rows. <code>LIMIT 6</code> shows Brazil and China</li>
</ul>
</div><div class="column" style="width:54%;">
<div style="font-size: 23px;">
<div id="46644837" class="cell" data-cache="true" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb13-2"><a></a><span class="st">    SELECT country, year,</span></span>
<span id="cb13-3"><a></a><span class="st">           ROUND(value, 0) AS gdp_pc</span></span>
<span id="cb13-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb13-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb13-6"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany',</span></span>
<span id="cb13-7"><a></a><span class="st">                      'India', 'Japan', 'United States')</span></span>
<span id="cb13-8"><a></a><span class="st">      AND year BETWEEN 2018 AND 2020</span></span>
<span id="cb13-9"><a></a><span class="st">    ORDER BY country, year</span></span>
<span id="cb13-10"><a></a><span class="st">    LIMIT 6</span></span>
<span id="cb13-11"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>┌─────────┬───────┬─────────┐
│ country │ year  │ gdp_pc  │
│ varchar │ int16 │ double  │
├─────────┼───────┼─────────┤
│ Brazil  │  2018 │  8722.0 │
│ Brazil  │  2019 │  8771.0 │
│ Brazil  │  2020 │  8435.0 │
│ China   │  2018 │  9799.0 │
│ China   │  2019 │ 10356.0 │
│ China   │  2020 │ 10573.0 │
└─────────┴───────┴─────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="like-and-ilike" class="slide level2">
<h2>LIKE and ILIKE</h2>
<h3 id="matching-part-of-a-text-value">Matching part of a text value</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:44%;">
<ul>
<li><span class="alert"><code>LIKE</code></span> matches part of a text value</li>
<li><code>%</code> means any characters, or none. <code>_</code> means exactly one character</li>
<li><code>'United%'</code> starts with United, <code>'%States'</code> ends with States, <code>'%King%'</code> contains King</li>
<li><span class="alert"><code>DISTINCT</code></span> removes duplicates. Without it, each country appears once per indicator and year</li>
<li><code>LIKE</code> is case-sensitive, so <code>'united%'</code> finds nothing</li>
<li><span class="alert"><code>ILIKE</code></span> ignores case, and finds the same three countries</li>
<li>In pandas: <code>.str.startswith()</code> or <code>.str.contains()</code></li>
</ul>
</div><div class="column" style="width:56%;">
<div style="font-size: 23px;">
<div id="208fa33c" class="cell" data-cache="true" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb15-2"><a></a><span class="st">    SELECT DISTINCT country</span></span>
<span id="cb15-3"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb15-4"><a></a><span class="st">    WHERE country LIKE 'United%'</span></span>
<span id="cb15-5"><a></a><span class="st">    ORDER BY country</span></span>
<span id="cb15-6"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>┌──────────────────────┐
│       country        │
│       varchar        │
├──────────────────────┤
│ United Arab Emirates │
│ United Kingdom       │
│ United States        │
└──────────────────────┘</code></pre>
</div>
</div>
<div id="3fb20da3" class="cell" data-cache="true" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb17-2"><a></a><span class="st">    SELECT DISTINCT country</span></span>
<span id="cb17-3"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb17-4"><a></a><span class="st">    WHERE country ILIKE 'united%'</span></span>
<span id="cb17-5"><a></a><span class="st">    ORDER BY country</span></span>
<span id="cb17-6"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>┌──────────────────────┐
│       country        │
│       varchar        │
├──────────────────────┤
│ United Arab Emirates │
│ United Kingdom       │
│ United States        │
└──────────────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="one-query-one-clause-at-a-time" class="slide level2">
<h2>One query, one clause at a time</h2>
<h3 id="every-clause-you-have-met-in-one-query">Every clause you have met, in one query</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:45%;">
<div style="text-align: center; font-size: 22px; margin-top: 10px; margin-bottom: 30px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Clause</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>FROM wdi</code></td>
<td>picks the table</td>
</tr>
<tr class="even">
<td><code>WHERE</code></td>
<td>keeps 6 of 59,024 rows</td>
</tr>
<tr class="odd">
<td><code>SELECT</code></td>
<td>picks 3 columns, rounds one</td>
</tr>
<tr class="even">
<td><code>ORDER BY</code></td>
<td>sorts by value</td>
</tr>
<tr class="odd">
<td><code>LIMIT</code></td>
<td>keeps 3 rows</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>You have met every clause here</li>
<li>Read a query from <code>FROM</code>, because that is where the engine starts</li>
<li>Three rows survive: the United States (59,534), Germany (42,373) and Japan (35,363)</li>
<li>We build on this query for the rest of the lecture</li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 23px;">
<div id="44b270dd" class="cell" data-cache="true" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb19-2"><a></a><span class="st">    SELECT country, year, ROUND(value, 0) AS gdp_pc</span></span>
<span id="cb19-3"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb19-4"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb19-5"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany',</span></span>
<span id="cb19-6"><a></a><span class="st">                      'India', 'Japan', 'United States')</span></span>
<span id="cb19-7"><a></a><span class="st">      AND year = 2020</span></span>
<span id="cb19-8"><a></a><span class="st">    ORDER BY value DESC</span></span>
<span id="cb19-9"><a></a><span class="st">    LIMIT 3</span></span>
<span id="cb19-10"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>┌───────────────┬───────┬─────────┐
│    country    │ year  │ gdp_pc  │
│    varchar    │ int16 │ double  │
├───────────────┼───────┼─────────┤
│ United States │  2020 │ 59534.0 │
│ Germany       │  2020 │ 42373.0 │
│ Japan         │  2020 │ 35363.0 │
└───────────────┴───────┴─────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="the-order-a-query-really-runs-in" class="slide level2">
<h2>The order a query really runs in</h2>
<h3 id="how-the-engine-evaluates-a-query">How the engine evaluates a query</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/sql-evaluation-order.png"><img data-src="figures/sql-evaluation-order.png" style="width:60.0%"></a></p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>You write <code>SELECT</code> first, but the engine runs it fifth</li>
<li><code>FROM</code> finds the rows, <code>WHERE</code> filters them, <code>GROUP BY</code> makes groups, <code>HAVING</code> filters groups, then <code>SELECT</code> builds the output</li>
<li><code>ORDER BY</code> sorts what <code>SELECT</code> produced, and <code>LIMIT</code> runs last of all</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>An aggregate cannot go in <code>WHERE</code>: the groups do not exist yet</li>
<li>Standard SQL rejects a <code>SELECT</code> alias in <code>WHERE</code>, because the alias does not exist yet. DuckDB allows it</li>
<li>pandas writes the steps in this order: <code>df[mask].groupby(...).agg(...)</code></li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="aggregating" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Aggregating</h1>

</section>
<section id="sec-group-by" class="slide level2">
<h2>GROUP BY</h2>
<h3 id="one-row-of-output-per-group">One row of output per group</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:48%;">
<ul>
<li>An <span class="alert">aggregate function</span> turns many rows into one number</li>
<li>The common ones: <code>COUNT</code>, <code>SUM</code>, <code>AVG</code> (mean), <code>MIN</code>, <code>MAX</code></li>
<li>Without <code>GROUP BY</code>, the whole table is one group, so you get one row</li>
<li><span class="alert"><code>GROUP BY country</code></span> makes six groups, so six rows</li>
<li>Every column in <code>SELECT</code> must be in <code>GROUP BY</code> or inside an aggregate
<ul>
<li><code>SELECT country, value ... GROUP BY country</code> fails: each group has 14 values, and SQL will not pick one</li>
</ul></li>
<li><code>n</code> is 14: the years 2010 to 2023. In pandas: <code>.groupby("country").agg(...)</code></li>
<li>Two grouping columns give one row per pair: <a href="#/sec-appendix-04"><span class="button">Appendix 04</span></a></li>
</ul>
</div><div class="column" style="width:52%;">
<div style="font-size: 23px;">
<div id="dca829a4" class="cell" data-cache="true" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb21-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb21-3"><a></a><span class="st">           COUNT(value) AS n,</span></span>
<span id="cb21-4"><a></a><span class="st">           ROUND(AVG(value), 0) AS mean_gdp</span></span>
<span id="cb21-5"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb21-6"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb21-7"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany',</span></span>
<span id="cb21-8"><a></a><span class="st">                      'India', 'Japan', 'United States')</span></span>
<span id="cb21-9"><a></a><span class="st">      AND year &gt;= 2010</span></span>
<span id="cb21-10"><a></a><span class="st">    GROUP BY country</span></span>
<span id="cb21-11"><a></a><span class="st">    ORDER BY mean_gdp DESC</span></span>
<span id="cb21-12"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>┌───────────────┬───────┬──────────┐
│    country    │   n   │ mean_gdp │
│    varchar    │ int64 │  double  │
├───────────────┼───────┼──────────┤
│ United States │    14 │  58330.0 │
│ Germany       │    14 │  42448.0 │
│ Japan         │    14 │  35682.0 │
│ China         │    14 │   9017.0 │
│ Brazil        │    14 │   8923.0 │
│ India         │    14 │   1694.0 │
└───────────────┴───────┴──────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="where-and-having" class="slide level2">
<h2>WHERE and HAVING</h2>
<h3 id="filtering-before-and-after-grouping">Filtering before and after grouping</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:48%;">
<ul>
<li><code>WHERE</code> filters rows <span class="alert">before</span> grouping. <span class="alert"><code>HAVING</code></span> filters groups <span class="alert">after</span></li>
<li>Only <code>HAVING</code> can use an aggregate, because the groups exist by then</li>
<li>“Which years count?” is about rows, so it goes in <code>WHERE</code></li>
<li>“Which countries qualify?” is about groups, so it goes in <code>HAVING</code></li>
<li><code>HAVING AVG(value) &gt; 30000</code> keeps three countries</li>
<li>China (9,017), Brazil (8,923) and India (1,694) drop out</li>
<li><code>ORDER BY</code> can use the alias <code>mean_gdp</code>, because it runs after <code>SELECT</code></li>
</ul>
</div><div class="column" style="width:52%;">
<div style="font-size: 23px;">
<div id="d293314e" class="cell" data-cache="true" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb23-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb23-3"><a></a><span class="st">           COUNT(value) AS n,</span></span>
<span id="cb23-4"><a></a><span class="st">           ROUND(AVG(value), 0) AS mean_gdp</span></span>
<span id="cb23-5"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb23-6"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb23-7"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany',</span></span>
<span id="cb23-8"><a></a><span class="st">                      'India', 'Japan', 'United States')</span></span>
<span id="cb23-9"><a></a><span class="st">      AND year &gt;= 2010</span></span>
<span id="cb23-10"><a></a><span class="st">    GROUP BY country</span></span>
<span id="cb23-11"><a></a><span class="st">    HAVING AVG(value) &gt; 30000</span></span>
<span id="cb23-12"><a></a><span class="st">    ORDER BY mean_gdp DESC</span></span>
<span id="cb23-13"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>┌───────────────┬───────┬──────────┐
│    country    │   n   │ mean_gdp │
│    varchar    │ int64 │  double  │
├───────────────┼───────┼──────────┤
│ United States │    14 │  58330.0 │
│ Germany       │    14 │  42448.0 │
│ Japan         │    14 │  35682.0 │
└───────────────┴───────┴──────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="count-and-countvalue" class="slide level2">
<h2>COUNT(*) and COUNT(value)</h2>
<h3 id="counting-rows-and-counting-values">Counting rows and counting values</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:48%;">
<ul>
<li><span class="alert"><code>COUNT(*)</code></span> counts rows</li>
<li><span class="alert"><code>COUNT(value)</code></span> counts only the rows where <code>value</code> is present</li>
<li>The difference is the number of missing values</li>
<li><code>AVG</code>, <code>SUM</code>, <code>MIN</code> and <code>MAX</code> skip missing values without warning</li>
<li>217 countries a year: 25 missing in 1990, 18 in 2000, 9 in 2020</li>
<li>So GDP coverage <span class="alert">improves</span> over time</li>
<li>In pandas: <code>len(df)</code> against <code>df["value"].count()</code></li>
<li>Check this before you trust a mean</li>
</ul>
</div><div class="column" style="width:52%;">
<div style="font-size: 23px;">
<div id="91f18e1a" class="cell" data-cache="true" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb25-2"><a></a><span class="st">    SELECT year,</span></span>
<span id="cb25-3"><a></a><span class="st">           COUNT(*) AS n_rows,</span></span>
<span id="cb25-4"><a></a><span class="st">           COUNT(value) AS with_value,</span></span>
<span id="cb25-5"><a></a><span class="st">           COUNT(*) - COUNT(value) AS missing</span></span>
<span id="cb25-6"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb25-7"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb25-8"><a></a><span class="st">      AND year IN (1990, 2000, 2020)</span></span>
<span id="cb25-9"><a></a><span class="st">    GROUP BY year</span></span>
<span id="cb25-10"><a></a><span class="st">    ORDER BY year</span></span>
<span id="cb25-11"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>┌───────┬────────┬────────────┬─────────┐
│ year  │ n_rows │ with_value │ missing │
│ int16 │ int64  │   int64    │  int64  │
├───────┼────────┼────────────┼─────────┤
│  1990 │    217 │        192 │      25 │
│  2000 │    217 │        199 │      18 │
│  2020 │    217 │        208 │       9 │
└───────┴────────┴────────────┴─────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="nulls-case-and-windows" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>NULLs, CASE and windows</h1>

</section>
<section id="missing-values" class="slide level2">
<h2>Missing values</h2>
<h3 id="working-with-null">Working with NULL</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:48%;">
<ul>
<li><span class="alert">NULL</span> means “unknown”. It is not zero, and not an empty string</li>
<li>Any comparison with NULL gives NULL, so <code>NULL = NULL</code> never matches</li>
<li>Test with <span class="alert"><code>IS NULL</code></span> or <span class="alert"><code>IS NOT NULL</code></span></li>
<li><span class="alert"><code>COALESCE(a, b)</code></span> returns <code>a</code>, or <code>b</code> if <code>a</code> is NULL</li>
<li>Yemen has no 2020 GDP figure, so it shows 0 here</li>
<li>Filling with 0 is a choice. A mean over this column would be wrong</li>
<li><code>COALESCE</code> fills a missing value. A missing <span class="alert">row</span> needs a <code>LEFT JOIN</code></li>
<li>In pandas, NULL is <code>NaN</code>, and <code>.fillna(0)</code> does this</li>
</ul>
</div><div class="column" style="width:52%;">
<div style="font-size: 23px;">
<div id="4b4f0aa3" class="cell" data-cache="true" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb27-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb27-3"><a></a><span class="st">           ROUND(COALESCE(value, 0), 0) AS gdp_filled</span></span>
<span id="cb27-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb27-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita' AND year = 2020</span></span>
<span id="cb27-6"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany', 'India',</span></span>
<span id="cb27-7"><a></a><span class="st">                      'Japan', 'United States', 'Yemen, Rep.')</span></span>
<span id="cb27-8"><a></a><span class="st">    ORDER BY country</span></span>
<span id="cb27-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>┌───────────────┬────────────┐
│    country    │ gdp_filled │
│    varchar    │   double   │
├───────────────┼────────────┤
│ Brazil        │     8435.0 │
│ China         │    10573.0 │
│ Germany       │    42373.0 │
│ India         │     1807.0 │
│ Japan         │    35363.0 │
│ United States │    59534.0 │
│ Yemen, Rep.   │        0.0 │
└───────────────┴────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="case" class="slide level2">
<h2>CASE</h2>
<h3 id="writing-an-if-else-ladder-inside-a-select">Writing an if-else ladder inside a SELECT</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><span class="alert"><code>CASE</code></span> is an if-else ladder inside <code>SELECT</code></li>
<li><code>WHEN</code> gives a condition, and <code>THEN</code> the value to use if it holds</li>
<li>Tests run top to bottom, and the first true one wins</li>
<li><code>ELSE</code> catches the rest, and <code>END</code> closes the ladder. Without <code>ELSE</code>, unmatched rows get NULL</li>
<li>The cut-offs are the World Bank’s FY24 income bands. The Bank applies them to GNI per capita, so here they are a rough guide</li>
<li><code>IS NULL</code> comes first on purpose. Lower down, Yemen would fall to <code>ELSE</code> as “Low income”</li>
<li>The result is a new column you can group, join, or export</li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 23px;">
<div id="d7ca228f" class="cell" data-cache="true" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb29-2"><a></a><span class="st">    SELECT country, ROUND(value, 0) AS gdp_pc,</span></span>
<span id="cb29-3"><a></a><span class="st">        CASE</span></span>
<span id="cb29-4"><a></a><span class="st">            WHEN value IS NULL  THEN 'No data'</span></span>
<span id="cb29-5"><a></a><span class="st">            WHEN value &gt;= 13846 THEN 'High income'</span></span>
<span id="cb29-6"><a></a><span class="st">            WHEN value &gt;= 4466  THEN 'Upper middle'</span></span>
<span id="cb29-7"><a></a><span class="st">            WHEN value &gt;= 1136  THEN 'Lower middle'</span></span>
<span id="cb29-8"><a></a><span class="st">            ELSE 'Low income'</span></span>
<span id="cb29-9"><a></a><span class="st">        END AS income_band</span></span>
<span id="cb29-10"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb29-11"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita' AND year = 2020</span></span>
<span id="cb29-12"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany', 'India',</span></span>
<span id="cb29-13"><a></a><span class="st">                      'Japan', 'United States', 'Yemen, Rep.')</span></span>
<span id="cb29-14"><a></a><span class="st">    ORDER BY value DESC NULLS LAST</span></span>
<span id="cb29-15"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>┌───────────────┬─────────┬──────────────┐
│    country    │ gdp_pc  │ income_band  │
│    varchar    │ double  │   varchar    │
├───────────────┼─────────┼──────────────┤
│ United States │ 59534.0 │ High income  │
│ Germany       │ 42373.0 │ High income  │
│ Japan         │ 35363.0 │ High income  │
│ China         │ 10573.0 │ Upper middle │
│ Brazil        │  8435.0 │ Upper middle │
│ India         │  1807.0 │ Lower middle │
│ Yemen, Rep.   │    NULL │ No data      │
└───────────────┴─────────┴──────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="sec-windows" class="slide level2">
<h2>Window functions</h2>
<h3 id="a-group-level-number-on-every-row">A group-level number on every row</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><code>GROUP BY year</code> would collapse these 12 rows into 2</li>
<li>A <span class="alert">window function</span> keeps every row and adds a group number beside it</li>
<li><span class="alert"><code>OVER</code></span> turns an aggregate into a window function</li>
<li><span class="alert"><code>PARTITION BY year</code></span> makes one <span class="alert">window</span>, a set of rows, per year. No rows are lost</li>
<li><code>year_mean</code> repeats on each row of its year: 20,885 in 2000, 26,347 in 2020</li>
<li>In pandas: <code>.groupby("year")["value"].transform("mean")</code></li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 23px;">
<div id="b71d01ec" class="cell" data-cache="true" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb31-2"><a></a><span class="st">    SELECT country, year, ROUND(value, 0) AS gdp_pc,</span></span>
<span id="cb31-3"><a></a><span class="st">           ROUND(AVG(value) OVER (PARTITION BY year), 0)</span></span>
<span id="cb31-4"><a></a><span class="st">               AS year_mean</span></span>
<span id="cb31-5"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb31-6"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb31-7"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany',</span></span>
<span id="cb31-8"><a></a><span class="st">                      'India', 'Japan', 'United States')</span></span>
<span id="cb31-9"><a></a><span class="st">      AND year IN (2000, 2020)</span></span>
<span id="cb31-10"><a></a><span class="st">    ORDER BY year, value DESC</span></span>
<span id="cb31-11"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>┌───────────────┬───────┬─────────┬───────────┐
│    country    │ year  │ gdp_pc  │ year_mean │
│    varchar    │ int16 │ double  │  double   │
├───────────────┼───────┼─────────┼───────────┤
│ United States │  2000 │ 48616.0 │   20885.0 │
│ Germany       │  2000 │ 35104.0 │   20885.0 │
│ Japan         │  2000 │ 31779.0 │   20885.0 │
│ Brazil        │  2000 │  6818.0 │   20885.0 │
│ China         │  2000 │  2237.0 │   20885.0 │
│ India         │  2000 │   757.0 │   20885.0 │
│ United States │  2020 │ 59534.0 │   26347.0 │
│ Germany       │  2020 │ 42373.0 │   26347.0 │
│ Japan         │  2020 │ 35363.0 │   26347.0 │
│ China         │  2020 │ 10573.0 │   26347.0 │
│ Brazil        │  2020 │  8435.0 │   26347.0 │
│ India         │  2020 │  1807.0 │   26347.0 │
└───────────────┴───────┴─────────┴───────────┘
  12 rows                           4 columns</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="ranking-with-a-window" class="slide level2">
<h2>Ranking with a window</h2>
<h3 id="rank-needs-an-order-by-inside-over">RANK() needs an ORDER BY inside OVER</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><span class="alert"><code>RANK()</code></span> numbers rows by the <code>ORDER BY</code> inside <code>OVER</code></li>
<li>The inner <code>ORDER BY</code> sets the ranks. The outer one sorts the printed table</li>
<li>No <code>PARTITION BY</code>: one window for the whole result</li>
<li>Ties share a rank, and the next is skipped: 1, 2, 2, 4</li>
<li><code>DENSE_RANK()</code> gives 1, 2, 2, 3, and <code>ROW_NUMBER()</code> never ties</li>
<li>The United States ranks 1 (59,534), and India 6 (1,807)</li>
<li><code>WHERE</code> runs first, so only these six countries are ranked</li>
<li>Add <code>PARTITION BY year</code> to rank within each year</li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 23px;">
<div id="fad31567" class="cell" data-cache="true" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb33-2"><a></a><span class="st">    SELECT country, ROUND(value, 0) AS gdp_pc,</span></span>
<span id="cb33-3"><a></a><span class="st">           RANK() OVER (ORDER BY value DESC) AS rank_2020</span></span>
<span id="cb33-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb33-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita'</span></span>
<span id="cb33-6"><a></a><span class="st">      AND country IN ('Brazil', 'China', 'Germany',</span></span>
<span id="cb33-7"><a></a><span class="st">                      'India', 'Japan', 'United States')</span></span>
<span id="cb33-8"><a></a><span class="st">      AND year = 2020</span></span>
<span id="cb33-9"><a></a><span class="st">    ORDER BY rank_2020</span></span>
<span id="cb33-10"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>┌───────────────┬─────────┬───────────┐
│    country    │ gdp_pc  │ rank_2020 │
│    varchar    │ double  │   int64   │
├───────────────┼─────────┼───────────┤
│ United States │ 59534.0 │         1 │
│ Germany       │ 42373.0 │         2 │
│ Japan         │ 35363.0 │         3 │
│ China         │ 10573.0 │         4 │
│ Brazil        │  8435.0 │         5 │
│ India         │  1807.0 │         6 │
└───────────────┴─────────┴───────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="joins" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Joins</h1>

</section>
<section id="two-small-tables" class="slide level2">
<h2>Two small tables</h2>
<h3 id="keys-and-the-two-tables-we-will-join">Keys, and the two tables we will join</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:42%;">
<ul>
<li>A <span class="alert">table</span> stores its data, unlike the <code>wdi</code> view</li>
<li><code>CREATE TABLE ... AS SELECT</code> builds <code>gdp2020</code> from a query</li>
<li><code>CREATE TABLE (col TYPE, ...)</code> declares empty columns. <code>INSERT INTO ... VALUES</code> adds rows</li>
<li>A <span class="alert">primary key</span> identifies each row, with no duplicates or NULLs: <code>iso3</code> in <code>regions</code></li>
<li>A <span class="alert">foreign key</span> points at another table’s primary key. <code>iso3</code> in <code>gdp2020</code> plays that role, but we never declare it, so <code>JPN</code> can sit there with no partner</li>
<li>Six rows in <code>gdp2020</code>, seven in <code>regions</code></li>
<li>Mismatches: <span class="alert"><code>JPN</code></span> has GDP but no region. <span class="alert"><code>KOR</code></span> and <span class="alert"><code>AUS</code></span> have a region but no GDP</li>
<li>East Asia holds two codes, which matters in the exercise</li>
</ul>
</div><div class="column" style="width:58%;">
<div style="font-size: 23px;">
<div id="bd374ae0" class="cell" data-cache="true" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb35-2"><a></a><span class="st">    CREATE OR REPLACE TABLE gdp2020 AS</span></span>
<span id="cb35-3"><a></a><span class="st">    SELECT country, iso3, ROUND(value, 0) AS gdp_per_capita</span></span>
<span id="cb35-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb35-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita' AND year = 2020</span></span>
<span id="cb35-6"><a></a><span class="st">      AND iso3 IN ('USA','BRA','CHN','IND','DEU','JPN')</span></span>
<span id="cb35-7"><a></a><span class="st">"""</span>)</span>
<span id="cb35-8"><a></a></span>
<span id="cb35-9"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb35-10"><a></a><span class="st">    CREATE OR REPLACE TABLE regions</span></span>
<span id="cb35-11"><a></a><span class="st">        (iso3 VARCHAR PRIMARY KEY, region VARCHAR)</span></span>
<span id="cb35-12"><a></a><span class="st">"""</span>)</span>
<span id="cb35-13"><a></a></span>
<span id="cb35-14"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb35-15"><a></a><span class="st">    INSERT INTO regions VALUES</span></span>
<span id="cb35-16"><a></a><span class="st">        ('USA', 'North America'), ('BRA', 'Latin America'),</span></span>
<span id="cb35-17"><a></a><span class="st">        ('CHN', 'East Asia'),     ('IND', 'South Asia'),</span></span>
<span id="cb35-18"><a></a><span class="st">        ('DEU', 'Europe'),        ('KOR', 'East Asia'),</span></span>
<span id="cb35-19"><a></a><span class="st">        ('AUS', 'Oceania')</span></span>
<span id="cb35-20"><a></a><span class="st">"""</span>)</span>
<span id="cb35-21"><a></a></span>
<span id="cb35-22"><a></a>duckdb.sql(<span class="st">"SELECT * FROM regions ORDER BY iso3"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>┌─────────┬───────────────┐
│  iso3   │    region     │
│ varchar │    varchar    │
├─────────┼───────────────┤
│ AUS     │ Oceania       │
│ BRA     │ Latin America │
│ CHN     │ East Asia     │
│ DEU     │ Europe        │
│ IND     │ South Asia    │
│ KOR     │ East Asia     │
│ USA     │ North America │
└─────────┴───────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="reading-a-join" class="slide level2">
<h2>Reading a join</h2>
<h3 id="the-on-clause-and-table-aliases">The ON clause and table aliases</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:46%;">
<ul>
<li>A <span class="alert"><code>JOIN</code></span> combines two tables into one wider result</li>
<li><span class="alert"><code>ON</code></span> says which columns must match: <code>iso3</code> on both sides</li>
<li>Each matching pair of rows becomes one output row</li>
<li><code>AS g</code> and <code>AS r</code> are <span class="alert">table aliases</span>: short names for the tables</li>
<li><code>g.country</code> means “<code>country</code> from <code>gdp2020</code>”. Prefix every column this way</li>
<li>The join type goes before <code>JOIN</code>. <code>INNER</code> is the default</li>
<li>In pandas: <code>pd.merge(gdp2020, regions, on="iso3")</code></li>
<li>The next three slides run this with three join types</li>
</ul>
</div><div class="column" style="width:54%;">
<div style="font-size: 23px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode numberSource sql number-lines code-with-copy"><code class="sourceCode sql"><span id="cb37-1"><a></a><span class="kw">SELECT</span> g.country, r.region, g.gdp_per_capita</span>
<span id="cb37-2"><a></a><span class="kw">FROM</span> gdp2020 <span class="kw">AS</span> g</span>
<span id="cb37-3"><a></a><span class="kw">INNER</span> <span class="kw">JOIN</span> regions <span class="kw">AS</span> r <span class="kw">ON</span> g.iso3 <span class="op">=</span> r.iso3</span>
<span id="cb37-4"><a></a><span class="kw">ORDER</span> <span class="kw">BY</span> g.country</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</div>
</section>
<section id="inner-join" class="slide level2">
<h2>INNER JOIN</h2>
<h3 id="only-the-rows-that-match-on-both-sides">Only the rows that match on both sides</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:46%;">
<ul>
<li>An <span class="alert"><code>INNER JOIN</code></span> keeps only the codes in both tables</li>
<li>Six rows on the left, seven on the right, <span class="alert">five</span> out</li>
<li>Japan drops out: <code>JPN</code> is not in <code>regions</code></li>
<li>Korea and Australia drop out too: they have no 2020 GDP row</li>
<li>An inner join filters silently, with no warning about lost rows</li>
<li>If your row count falls after a join, this is usually why</li>
<li>In pandas: <code>pd.merge(..., how="inner")</code></li>
</ul>
</div><div class="column" style="width:54%;">
<div style="font-size: 24px;">
<div id="b342aa31" class="cell" data-cache="true" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb38-2"><a></a><span class="st">    SELECT g.country, r.region, g.gdp_per_capita</span></span>
<span id="cb38-3"><a></a><span class="st">    FROM gdp2020 AS g</span></span>
<span id="cb38-4"><a></a><span class="st">    INNER JOIN regions AS r ON g.iso3 = r.iso3</span></span>
<span id="cb38-5"><a></a><span class="st">    ORDER BY g.country</span></span>
<span id="cb38-6"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>┌───────────────┬───────────────┬────────────────┐
│    country    │    region     │ gdp_per_capita │
│    varchar    │    varchar    │     double     │
├───────────────┼───────────────┼────────────────┤
│ Brazil        │ Latin America │         8435.0 │
│ China         │ East Asia     │        10573.0 │
│ Germany       │ Europe        │        42373.0 │
│ India         │ South Asia    │         1807.0 │
│ United States │ North America │        59534.0 │
└───────────────┴───────────────┴────────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="left-join" class="slide level2">
<h2>LEFT JOIN</h2>
<h3 id="keeping-every-row-of-the-left-table">Keeping every row of the left table</h3>
<div style="margin-top: 40px; font-size: 23px;">
<div class="columns">
<div class="column" style="width:46%;">
<ul>
<li>A <span class="alert"><code>LEFT JOIN</code></span> keeps every row of the left table</li>
<li>The left table is the one in <code>FROM</code>: <code>gdp2020</code> here</li>
<li><span class="alert">Six</span> rows: Japan is back, with <code>NULL</code> for <code>region</code></li>
<li>That NULL means “no partner found”. Japan’s 35,363 is unchanged</li>
<li>Korea and Australia are still missing: they exist only on the right</li>
<li>Swap the tables and you get a different answer, as in the exercise</li>
<li>The join you will use most: it adds labels without losing rows</li>
<li>In pandas: <code>pd.merge(..., how="left")</code></li>
</ul>
</div><div class="column" style="width:54%;">
<div style="font-size: 24px;">
<div id="56353f2e" class="cell" data-cache="true" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb40-2"><a></a><span class="st">    SELECT g.country, r.region, g.gdp_per_capita</span></span>
<span id="cb40-3"><a></a><span class="st">    FROM gdp2020 AS g</span></span>
<span id="cb40-4"><a></a><span class="st">    LEFT JOIN regions AS r ON g.iso3 = r.iso3</span></span>
<span id="cb40-5"><a></a><span class="st">    ORDER BY g.country</span></span>
<span id="cb40-6"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>┌───────────────┬───────────────┬────────────────┐
│    country    │    region     │ gdp_per_capita │
│    varchar    │    varchar    │     double     │
├───────────────┼───────────────┼────────────────┤
│ Brazil        │ Latin America │         8435.0 │
│ China         │ East Asia     │        10573.0 │
│ Germany       │ Europe        │        42373.0 │
│ India         │ South Asia    │         1807.0 │
│ Japan         │ NULL          │        35363.0 │
│ United States │ North America │        59534.0 │
└───────────────┴───────────────┴────────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="full-outer-join" class="slide level2">
<h2>FULL OUTER JOIN</h2>
<h3 id="every-row-from-both-tables-survives">Every row from both tables survives</h3>
<div style="margin-top: 40px; font-size: 19px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li>A <span class="alert"><code>FULL OUTER JOIN</code></span> keeps every row from both tables, with NULLs where there is no partner</li>
<li><span class="alert">Eight</span> rows: five pairs, plus Japan, Korea and Australia</li>
<li>Korea and Australia have a region, but NULL <code>country</code> and <code>gdp_per_capita</code></li>
<li>Japan has a country and 35,363, but NULL region columns</li>
<li>On these tables: 5 rows from <code>INNER</code>, 6 from <code>LEFT</code>, 8 from <code>FULL OUTER</code></li>
<li>To choose a join, ask which table must survive whole, and what to do with rows that have no partner</li>
</ul>
<div style="text-align: center; margin-top: 10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/sql-joins.png"><img data-src="figures/sql-joins.png" style="width:80.0%"></a></p>
<div style="font-size: 15px;">
<p>Our two tables and the three joins. Click to enlarge</p>
</div>
</div>
</div><div class="column" style="width:55%;">
<div style="font-size: 23px;">
<div id="a3bfa488" class="cell" data-cache="true" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb42-2"><a></a><span class="st">    SELECT g.country, r.iso3 AS region_iso3,</span></span>
<span id="cb42-3"><a></a><span class="st">           r.region, g.gdp_per_capita</span></span>
<span id="cb42-4"><a></a><span class="st">    FROM gdp2020 AS g</span></span>
<span id="cb42-5"><a></a><span class="st">    FULL OUTER JOIN regions AS r ON g.iso3 = r.iso3</span></span>
<span id="cb42-6"><a></a><span class="st">    ORDER BY r.region NULLS LAST, r.iso3</span></span>
<span id="cb42-7"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>┌───────────────┬─────────────┬───────────────┬────────────────┐
│    country    │ region_iso3 │    region     │ gdp_per_capita │
│    varchar    │   varchar   │    varchar    │     double     │
├───────────────┼─────────────┼───────────────┼────────────────┤
│ China         │ CHN         │ East Asia     │        10573.0 │
│ NULL          │ KOR         │ East Asia     │           NULL │
│ Germany       │ DEU         │ Europe        │        42373.0 │
│ Brazil        │ BRA         │ Latin America │         8435.0 │
│ United States │ USA         │ North America │        59534.0 │
│ NULL          │ AUS         │ Oceania       │           NULL │
│ India         │ IND         │ South Asia    │         1807.0 │
│ Japan         │ NULL        │ NULL          │        35363.0 │
└───────────────┴─────────────┴───────────────┴────────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="sec-exercise-01" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="ten-minutes">Ten minutes</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<p>How rich is each region, and how much data is it based on?</p>
<ol type="1">
<li>Use the <code>gdp2020</code> and <code>regions</code> tables from the joins section</li>
<li>Report one row per region</li>
<li>Count how many of that region’s countries have a 2020 GDP figure</li>
<li>Compute the mean GDP per capita of that region</li>
<li>Keep every region, including the one with no GDP data at all</li>
<li>Sort by mean GDP, highest first</li>
<li>Send the region with no data to the bottom of the list</li>
</ol>
</div><div class="column" style="width:48%;">
<p>What to look for:</p>
<ul>
<li>Which table goes on the left if every region must survive?</li>
<li>East Asia has two codes but one GDP figure, so <code>COUNT(*)</code> and <code>COUNT(g.country)</code> differ</li>
<li>Oceania has no GDP figure at all</li>
<li>Six regions come back</li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;">
<p>Solution: <a href="#/sec-appendix-01"><span class="button">Appendix 01</span></a></p>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="duckdb-and-pandas" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>DuckDB and pandas 🐼</h1>

</section>
<section id="querying-a-dataframe-by-name" class="slide level2">
<h2>Querying a DataFrame by name</h2>
<h3 id="your-python-variable-becomes-a-sql-table">Your Python variable becomes a SQL table</h3>
<div style="margin-top: 40px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li>DuckDB finds <code>df</code> among your Python variables and queries it by name</li>
<li>No registration, no copy, no conversion: it reads the DataFrame in memory</li>
<li>The same <code>SELECT</code> works on a file, a view or a DataFrame</li>
<li><code>SELECT COUNT(*) FROM df</code> gives 59,024, like the Parquet file</li>
<li>You can join two DataFrames in one query</li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 24px;">
<div id="91ef1ffd" class="cell" data-cache="true" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb44-2"><a></a></span>
<span id="cb44-3"><a></a>df <span class="op">=</span> pd.read_parquet(</span>
<span id="cb44-4"><a></a>    <span class="st">"../lecture-19/data/wdi_panel.parquet"</span></span>
<span id="cb44-5"><a></a>)</span>
<span id="cb44-6"><a></a></span>
<span id="cb44-7"><a></a>duckdb.sql(<span class="st">"SELECT COUNT(*) AS n FROM df"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>┌───────┐
│   n   │
│ int64 │
├───────┤
│ 59024 │
└───────┘</code></pre>
</div>
</div>
</div>
<div style="background: rgba(230, 57, 70, 0.1); padding: 12px; border-radius: 10px; font-size: 18px; margin-top: 8px;">
<p><code>country</code> is a pandas <span class="alert">category</span>: a text column with a fixed list of allowed values. DuckDB calls this type an <span class="alert">enum</span> (short for enumeration). Add <code>::VARCHAR</code> to turn it into plain text</p>
</div>
</div></div>
</div>
</section>
<section id="sec-pandas" class="slide level2">
<h2>Handing the result back to pandas</h2>
<h3 id="turning-a-result-into-a-dataframe">Turning a result into a DataFrame</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><span class="alert"><code>.df()</code></span> turns a DuckDB result into a pandas DataFrame</li>
<li><code>.pl()</code> gives a Polars DataFrame, and <code>.to_arrow_table()</code> an Arrow table</li>
<li>Without <code>.df()</code>, you get a DuckDB result that prints as a text table</li>
<li><code>country::VARCHAR</code> turns the category back into plain text</li>
<li>SQL returns 18 rows, and <code>pivot</code> reshapes them into 6 rows by 3 columns</li>
<li>DuckDB has a <code>PIVOT</code> statement too, but reshaping reads more easily in pandas</li>
<li>After <code>.df()</code>, it is ordinary pandas: <code>.plot()</code>, <code>.to_csv()</code>, <code>seaborn</code>, <code>statsmodels</code></li>
<li>SQL or pandas? <a href="#/sec-appendix-06"><span class="button">Appendix 06</span></a></li>
</ul>
</div><div class="column" style="width:55%;">
<div style="font-size: 21px;">
<div id="5a301c5e" class="cell" data-cache="true" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a></a><span class="bu">long</span> <span class="op">=</span> duckdb.sql(<span class="st">"""</span></span>
<span id="cb46-2"><a></a><span class="st">    SELECT country::VARCHAR AS country, indicator,</span></span>
<span id="cb46-3"><a></a><span class="st">           ROUND(value, 1) AS value</span></span>
<span id="cb46-4"><a></a><span class="st">    FROM df</span></span>
<span id="cb46-5"><a></a><span class="st">    WHERE year = 2020</span></span>
<span id="cb46-6"><a></a><span class="st">      AND iso3 IN ('USA', 'BRA', 'CHN',</span></span>
<span id="cb46-7"><a></a><span class="st">                   'IND', 'DEU', 'JPN')</span></span>
<span id="cb46-8"><a></a><span class="st">      AND indicator IN ('gdp_per_capita',</span></span>
<span id="cb46-9"><a></a><span class="st">                        'life_expectancy',</span></span>
<span id="cb46-10"><a></a><span class="st">                        'internet_users_pct')</span></span>
<span id="cb46-11"><a></a><span class="st">"""</span>).df()</span>
<span id="cb46-12"><a></a></span>
<span id="cb46-13"><a></a><span class="bu">long</span>.pivot(index<span class="op">=</span><span class="st">"country"</span>, columns<span class="op">=</span><span class="st">"indicator"</span>,</span>
<span id="cb46-14"><a></a>           values<span class="op">=</span><span class="st">"value"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th">indicator</th>
<th data-quarto-table-cell-role="th">gdp_per_capita</th>
<th data-quarto-table-cell-role="th">internet_users_pct</th>
<th data-quarto-table-cell-role="th">life_expectancy</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Brazil</th>
<td>8435.0</td>
<td>81.3</td>
<td>74.5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">China</th>
<td>10573.4</td>
<td>70.1</td>
<td>78.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Germany</th>
<td>42372.9</td>
<td>89.8</td>
<td>81.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">India</th>
<td>1806.5</td>
<td>43.4</td>
<td>70.2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Japan</th>
<td>35363.3</td>
<td>90.2</td>
<td>84.6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">United States</th>
<td>59533.6</td>
<td>90.3</td>
<td>77.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="sec-benchmark" class="slide level2">
<h2>DuckDB on 200 million rows</h2>
<h3 id="the-same-sql-on-a-200-million-row-file">The same SQL on a 200-million-row file</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:55%;">
<div style="text-align: center;">
<div id="9bdb9b57" class="cell" data-cache="true" data-execution_count="25">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="22-sql-revision_files/figure-revealjs/cell-25-output-1.png" width="662" height="392"></p>
</figure>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div style="font-size: 20px;">
<ul>
<li>Task: mean <code>value</code> by indicator and decade, on <code>wdi_big.parquet</code>, a synthetic panel of <span class="alert">200,681,600 rows</span></li>
<li><span class="alert">DuckDB</span>: 0.53 s. <span class="alert">Dask</span>: 5.39 s. <span class="alert">pandas</span>: 9.65 s</li>
<li>pandas loads every column into RAM. DuckDB reads only the three columns the query uses</li>
<li>Why: columnar storage, vectorised execution, and all cores by default</li>
<li>MacBook Pro, Apple M5, 10 cores, 24 GB RAM, macOS 26.6</li>
<li>Your seconds will differ, but the ranking usually holds</li>
<li><span class="alert">Polars</span> is in the same range as DuckDB (Tutorial 07)</li>
<li>The query and scripts: <a href="#/sec-appendix-07"><span class="button">Appendix 07</span></a></li>
</ul>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Summary</h1>

</section>
<section id="what-we-learned-today" class="slide level2">
<h2>What we learned today</h2>
<h3 id="the-vocabulary-in-the-order-we-met-it">The vocabulary, in the order we met it</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">SQL</span> is declarative: you describe the answer and the engine plans the work</li>
<li><span class="alert">DuckDB</span> needs one import and reads a Parquet file or a pandas DataFrame by name</li>
<li>A <span class="alert">view</span> names a query. <code>DESCRIBE</code> and <code>SUMMARIZE</code> show what is in it</li>
<li><span class="alert"><code>WHERE</code></span> filters rows, <span class="alert"><code>GROUP BY</code></span> forms groups, <span class="alert"><code>HAVING</code></span> filters groups. No aggregate in <code>WHERE</code></li>
<li><code>COUNT(*)</code> minus <code>COUNT(value)</code> is the number of missing values</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>A <span class="alert">NULL</span> means unknown. <code>COALESCE</code> fills one in, and a missing row needs a join instead</li>
<li><span class="alert"><code>CASE</code></span> builds a category column from an if-else ladder</li>
<li>A <span class="alert">window function</span> keeps every row: <code>AVG ... OVER (PARTITION BY year)</code> adds the year mean, <code>RANK()</code> a position</li>
<li>Joins: 5 rows from <code>INNER</code>, 6 from <code>LEFT</code>, 8 from <code>FULL OUTER</code> on the same two tables</li>
<li>On 200 million rows, DuckDB runs the same query in <span class="alert">0.53 seconds</span></li>
</ul>
</div></div>
</div>
</section>
<section id="sec-next-class" class="slide level2 scrollable">
<h2>Next class</h2>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Lecture 23</span>: dependency management, virtual environments and containers</li>
<li>Today’s queries depended on your Python, your DuckDB version and your laptop</li>
<li>Next class we package all three into an <span class="alert">image</span>, so anyone who runs it gets the same answer</li>
<li><code>pip install duckdb</code> stops being a setup instruction and becomes a line in a <code>Dockerfile</code></li>
</ul>
</div><div class="column" style="width:50%;">
<div style="margin-top: -15px;">
<p>Before then:</p>
<ol type="1">
<li>Finish the join exercise if you did not complete it in class</li>
<li>Work through <a href="https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html">Tutorial 04</a>, the DuckDB SQL tutorial on the course website</li>
<li>Check that <code>import duckdb</code> works in your environment</li>
<li>More practice with <code>GROUP BY</code> and <code>HAVING</code>: <a href="#/sec-appendix-02"><span class="button">Appendix 02</span></a>. Common error messages: <a href="#/sec-appendix-03"><span class="button">Appendix 03</span></a></li>
</ol>
</div>
</div></div>
</div>
</section></section>
<section id="thank-you-very-much" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Thank you very much! 😊</h1>

</section>

<section>
<section id="appendix" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Appendix 📚</h1>

</section>
<section id="sec-appendix-01" class="slide level2">
<h2>Appendix 01: Solution to the exercise</h2>
<div style="margin-top: 40px; font-size: 19px;">
<div class="columns">
<div class="column" style="width:46%;">
<ul>
<li><code>regions</code> goes on the left, because every region must survive</li>
<li>East Asia has two rows in <code>regions</code>, but <code>COUNT(g.country)</code> is 1: Korea’s row has a NULL country</li>
<li><code>COUNT(*)</code> would count that row and report 2</li>
<li>Oceania has no GDP figure: its count is 0 and its mean is NULL</li>
<li><code>NULLS LAST</code> sends Oceania to the bottom</li>
<li>Six regions, from North America (59,534) down to South Asia (1,807), then Oceania</li>
<li>Codes that appear in only one table? <a href="#/sec-appendix-05"><span class="button">Appendix 05</span></a></li>
</ul>
<p><a href="#/sec-exercise-01"><span class="button">Back to the exercise</span></a></p>
</div><div class="column" style="width:54%;">
<div style="font-size: 20px;">
<div id="b6fad87b" class="cell" data-cache="true" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb47-2"><a></a><span class="st">    SELECT r.region,</span></span>
<span id="cb47-3"><a></a><span class="st">           COUNT(g.country) AS countries_with_gdp,</span></span>
<span id="cb47-4"><a></a><span class="st">           ROUND(AVG(g.gdp_per_capita), 0) AS mean_gdp</span></span>
<span id="cb47-5"><a></a><span class="st">    FROM regions AS r</span></span>
<span id="cb47-6"><a></a><span class="st">    LEFT JOIN gdp2020 AS g ON g.iso3 = r.iso3</span></span>
<span id="cb47-7"><a></a><span class="st">    GROUP BY r.region</span></span>
<span id="cb47-8"><a></a><span class="st">    ORDER BY mean_gdp DESC NULLS LAST</span></span>
<span id="cb47-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>┌───────────────┬────────────────────┬──────────┐
│    region     │ countries_with_gdp │ mean_gdp │
│    varchar    │       int64        │  double  │
├───────────────┼────────────────────┼──────────┤
│ North America │                  1 │  59534.0 │
│ Europe        │                  1 │  42373.0 │
│ East Asia     │                  1 │  10573.0 │
│ Latin America │                  1 │   8435.0 │
│ South Asia    │                  1 │   1807.0 │
│ Oceania       │                  0 │     NULL │
└───────────────┴────────────────────┴──────────┘</code></pre>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="sec-appendix-02" class="slide level2 scrollable">
<h2>Appendix 02: Practice at home: GROUP BY and HAVING</h2>
<h3 id="one-more-question-to-try-on-your-own">One more question to try on your own</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:46%;">
<p>Which countries have had the highest life expectancy since 2010?</p>
<ol type="1">
<li>Create the <code>wdi</code> view over the panel</li>
<li>Keep only the <code>life_expectancy</code> rows</li>
<li>Keep only the years from 2010 onwards</li>
<li>Compute the mean of <code>value</code> for each country</li>
<li>Keep the countries whose mean is above 82</li>
<li>Sort from highest to lowest</li>
<li>Return the top five, rounded to one decimal</li>
</ol>
</div><div class="column" style="width:54%;">
<div style="font-size: 20px;">
<div id="17bdbdb2" class="cell" data-cache="true" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb49-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb49-3"><a></a><span class="st">           ROUND(AVG(value), 1) AS mean_life_exp</span></span>
<span id="cb49-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb49-5"><a></a><span class="st">    WHERE indicator = 'life_expectancy'</span></span>
<span id="cb49-6"><a></a><span class="st">      AND year &gt;= 2010</span></span>
<span id="cb49-7"><a></a><span class="st">    GROUP BY country</span></span>
<span id="cb49-8"><a></a><span class="st">    HAVING AVG(value) &gt; 82</span></span>
<span id="cb49-9"><a></a><span class="st">    ORDER BY mean_life_exp DESC</span></span>
<span id="cb49-10"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb49-11"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>┌──────────────────────┬───────────────┐
│       country        │ mean_life_exp │
│       varchar        │    double     │
├──────────────────────┼───────────────┤
│ Monaco               │          85.5 │
│ San Marino           │          84.4 │
│ Hong Kong SAR, China │          84.3 │
│ Japan                │          83.8 │
│ Andorra              │          83.8 │
└──────────────────────┴───────────────┘</code></pre>
</div>
</div>
</div>
<ul>
<li><code>WHERE</code> drops rows, <code>HAVING AVG(value) &gt; 82</code> tests the group</li>
<li><code>ORDER BY</code> names <code>mean_life_exp</code>, the alias created in <code>SELECT</code></li>
<li>Hong Kong and Japan are the only places in the top five with more than a million people</li>
</ul>
</div></div>
<div style="text-align: center; margin-top: 15px;">
<p><a href="#/sec-next-class"><span class="button">Back to Next class</span></a></p>
</div>
</div>
</section>
<section id="sec-appendix-03" class="slide level2">
<h2>Appendix 03: When something goes wrong</h2>
<div style="margin-top: 40px; font-size: 19px;">
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="alert"><code>Parser Error: syntax error at or near ".."</code></span></p>
<p>The file path is not quoted. Put single quotes around it: <code>FROM '../data/f.parquet'</code>.</p>
<p><span class="alert"><code>IO Error: No files found that match the pattern</code></span></p>
<p>The path is quoted but wrong. Paths are relative to the working directory (the notebook’s folder in Jupyter), so check with <code>os.getcwd()</code>.</p>
<p><span class="alert"><code>Binder Error: Referenced column "gdp" not found</code></span></p>
<p>The column name is misspelled or does not exist. Run <code>DESCRIBE SELECT * FROM wdi</code> and read the list</p>
</div><div class="column" style="width:50%;">
<p><span class="alert"><code>Parser Error: syntax error at or near "SELCT"</code></span></p>
<p>A keyword is misspelled. DuckDB quotes the offending word back at you, so read the message to the end.</p>
<p><span class="alert"><code>Binder Error</code> on a value you know exists</span></p>
<p>You wrote <code>WHERE indicator = "gdp_per_capita"</code> with double quotes. Double quotes mean a column name in SQL, single quotes mean text.</p>
<p><span class="alert"><code>Catalog Error: Table with name wdi does not exist</code></span></p>
<p>The view lives in the session that created it. Re-run the <code>CREATE VIEW</code> cell after restarting Python</p>
</div></div>
<div style="text-align: center; margin-top: 15px;">
<p><a href="#/sec-next-class"><span class="button">Back to Next class</span></a></p>
</div>
</div>
</section>
<section id="sec-appendix-04" class="slide level2">
<h2>Appendix 04: Grouping by two columns</h2>
<h3 id="every-combination-that-exists-in-the-data">Every combination that exists in the data</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Name two columns and you get one row for each pair that appears in the filtered rows</li>
<li>Two countries and two indicators give four rows here</li>
<li>Combinations with no rows never appear. SQL does not invent empty groups</li>
<li>Japan’s mean life expectancy since 2010 is nine years above Brazil’s. Its CO2 per person is almost four times higher</li>
<li>A mean over years like this weights every year equally. Say so when you report it</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 22px;">
<div id="64d2e714" class="cell" data-cache="true" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb51-2"><a></a><span class="st">    SELECT country, indicator,</span></span>
<span id="cb51-3"><a></a><span class="st">           ROUND(AVG(value), 1) AS mean_value</span></span>
<span id="cb51-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb51-5"><a></a><span class="st">    WHERE year &gt;= 2010</span></span>
<span id="cb51-6"><a></a><span class="st">      AND country IN ('Brazil', 'Japan')</span></span>
<span id="cb51-7"><a></a><span class="st">      AND indicator IN ('life_expectancy',</span></span>
<span id="cb51-8"><a></a><span class="st">                        'co2_per_capita')</span></span>
<span id="cb51-9"><a></a><span class="st">    GROUP BY country, indicator</span></span>
<span id="cb51-10"><a></a><span class="st">    ORDER BY country, indicator</span></span>
<span id="cb51-11"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>┌─────────┬─────────────────┬────────────┐
│ country │    indicator    │ mean_value │
│ varchar │     varchar     │   double   │
├─────────┼─────────────────┼────────────┤
│ Brazil  │ co2_per_capita  │        2.4 │
│ Brazil  │ life_expectancy │       74.8 │
│ Japan   │ co2_per_capita  │        9.3 │
│ Japan   │ life_expectancy │       83.8 │
└─────────┴─────────────────┴────────────┘</code></pre>
</div>
</div>
</div>
</div></div>
<div style="text-align: center; margin-top: 15px;">
<p><a href="#/sec-group-by"><span class="button">Back to GROUP BY</span></a></p>
</div>
</div>
</section>
<section id="sec-appendix-05" class="slide level2">
<h2>Appendix 05: Anti-joins and UNION</h2>
<h3 id="finding-rows-with-no-partner">Finding rows with no partner</h3>
<div style="margin-top: 40px; font-size: 19px;">
<div class="columns">
<div class="column" style="width:44%;">
<ul>
<li>An <span class="alert">anti-join</span> asks which rows on the left have no partner on the right</li>
<li><code>NOT EXISTS</code> runs a small query for each row and keeps the row when it returns nothing</li>
<li>Japan is the only such row here, because <code>JPN</code> is missing from <code>regions</code></li>
<li>A join adds columns. <span class="alert"><code>UNION</code></span> stacks rows from two results that have the same columns</li>
<li><code>UNION</code> removes duplicate rows, <code>UNION ALL</code> keeps them and is faster</li>
<li>The tagged result has five rows: Germany, Japan and the United States rich, Brazil and India poor</li>
<li>China falls in neither band, so it appears in no row at all</li>
</ul>
</div><div class="column" style="width:56%;">
<div style="font-size: 20px;">
<div id="0e9a2694" class="cell" data-cache="true" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb53-2"><a></a><span class="st">    SELECT g.country, g.iso3</span></span>
<span id="cb53-3"><a></a><span class="st">    FROM gdp2020 AS g</span></span>
<span id="cb53-4"><a></a><span class="st">    WHERE NOT EXISTS (</span></span>
<span id="cb53-5"><a></a><span class="st">        SELECT 1 FROM regions AS r</span></span>
<span id="cb53-6"><a></a><span class="st">        WHERE r.iso3 = g.iso3</span></span>
<span id="cb53-7"><a></a><span class="st">    )</span></span>
<span id="cb53-8"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>┌─────────┬─────────┐
│ country │  iso3   │
│ varchar │ varchar │
├─────────┼─────────┤
│ Japan   │ JPN     │
└─────────┴─────────┘</code></pre>
</div>
</div>
<div id="916c4dd2" class="cell" data-cache="true" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb55-2"><a></a><span class="st">    SELECT country, 'rich' AS tag FROM gdp2020</span></span>
<span id="cb55-3"><a></a><span class="st">    WHERE gdp_per_capita &gt; 30000</span></span>
<span id="cb55-4"><a></a><span class="st">    UNION</span></span>
<span id="cb55-5"><a></a><span class="st">    SELECT country, 'poor' AS tag FROM gdp2020</span></span>
<span id="cb55-6"><a></a><span class="st">    WHERE gdp_per_capita &lt; 10000</span></span>
<span id="cb55-7"><a></a><span class="st">    ORDER BY country</span></span>
<span id="cb55-8"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>┌───────────────┬─────────┐
│    country    │   tag   │
│    varchar    │ varchar │
├───────────────┼─────────┤
│ Brazil        │ poor    │
│ Germany       │ rich    │
│ India         │ poor    │
│ Japan         │ rich    │
│ United States │ rich    │
└───────────────┴─────────┘</code></pre>
</div>
</div>
</div>
</div></div>
<div style="text-align: center; margin-top: 15px;">
<p><a href="#/sec-appendix-01"><span class="button">Back to the exercise solution</span></a></p>
</div>
</div>
</section>
<section id="sec-appendix-06" class="slide level2">
<h2>Appendix 06: When SQL beats a DataFrame</h2>
<h3 id="a-checklist-for-each-tool">A checklist for each tool</h3>
<div style="margin-top: 40px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<p>Reach for SQL when:</p>
<ul>
<li>You are joining two or more tables</li>
<li>You are filtering and aggregating a file that is larger than your RAM</li>
<li>The question is a <code>GROUP BY</code> with a couple of conditions</li>
<li>Someone else has to read the query. A colleague who has never seen pandas can still read your <code>SELECT</code></li>
<li>The data already lives in a database</li>
</ul>
</div><div class="column" style="width:50%;">
<p>Stay in pandas when:</p>
<ul>
<li>You need row-by-row logic that has no set-based version</li>
<li>You are plotting, or feeding a model</li>
<li>You want many small inspectable steps, each one a variable you can look at</li>
<li>The reshaping is the hard part, as in the <code>pivot</code> in the DuckDB and pandas section</li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;">
<p>Want more practice? The course website has a full self-study <a href="https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html">DuckDB SQL tutorial</a> covering everything on these slides in more depth</p>
</div>
</div></div>
<div style="text-align: center; margin-top: 15px;">
<p><a href="#/sec-pandas"><span class="button">Back to the pandas slide</span></a></p>
</div>
</div>
</section>
<section id="sec-appendix-07" class="slide level2">
<h2>Appendix 07: The benchmark query</h2>
<h3 id="the-query-and-where-the-timings-come-from">The query and where the timings come from</h3>
<div style="margin-top: 40px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>The DuckDB version is the query you already know, with a file path in <code>FROM</code> and a <code>GROUP BY</code> at the end</li>
<li>The data is <code>wdi_big.parquet</code>, a synthetic panel of 200,681,600 rows built by cloning the small panel many times</li>
<li>The file is not committed, and the script that rebuilds it is in <a href="https://github.com/danilofreire/datasci350/blob/main/lectures/lecture-22/data/make_big_parquet.py"><code>data/make_big_parquet.py</code></a></li>
<li>The timings were measured once and saved to <a href="https://raw.githubusercontent.com/danilofreire/datasci350/main/lectures/lecture-22/data/benchmark_results.csv"><code>data/benchmark_results.csv</code></a>. The deck reads that file rather than re-running anything</li>
<li>pandas loads the whole thing and calls <code>groupby</code>, Dask uses a parallel DataFrame, and DuckDB runs SQL straight over the file</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 22px;">
<div id="043bc242" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a></a><span class="im">import</span> duckdb</span>
<span id="cb57-2"><a></a></span>
<span id="cb57-3"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb57-4"><a></a><span class="st">    SELECT indicator,</span></span>
<span id="cb57-5"><a></a><span class="st">           (year // 10) * 10 AS decade,</span></span>
<span id="cb57-6"><a></a><span class="st">           AVG(value) AS mean_value</span></span>
<span id="cb57-7"><a></a><span class="st">    FROM 'data/wdi_big.parquet'</span></span>
<span id="cb57-8"><a></a><span class="st">    WHERE year &gt;= 1990</span></span>
<span id="cb57-9"><a></a><span class="st">    GROUP BY indicator, decade</span></span>
<span id="cb57-10"><a></a><span class="st">"""</span>).df()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div></div>
<div style="text-align: center; margin-top: 15px;">
<p><a href="#/sec-benchmark"><span class="button">Back to the benchmark</span></a></p>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://danilofreire.github.io/datasci350/lectures/lecture-22/22-sql-revision.html">SQL with DuckDB</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/multimodal/multimodal.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, Multimodal, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>